# Generated by Django 4.2 on 2026-04-02

from django.db import migrations, models
import django.utils.timezone


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: chatsession updated at chatmessage payload and more).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này vào database.
class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_aiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(
                choices=[
                    ('chat', 'Chat AI'),
                    ('rag', 'Hỏi đáp RAG'),
                    ('assistant', 'Trợ lý AI'),
                    ('voice', 'Giọng nói AI'),
                ],
                default='chat',
                max_length=10,
            ),
        ),
    ]
