# Generated by Django 6.0.3 on 2026-04-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0007_rag_search_extensions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
