# Generated by Django 4.2.29 on 2026-05-13 12:36

import ai_engine.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_seed_default_company_memberships'),
        ('ai_engine', '0009_chatsession_assistant_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='chataudioattachment',
            name='audio_file',
            field=models.FileField(upload_to=ai_engine.models._chat_audio_upload),
        ),
    ]
