# Generated by Django 4.2.29 on 2026-05-13 12:39

import ai_engine.models
from django.db import migrations, models


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: alter chataudioattachment audio file).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này vào database.
class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0010_chatsession_company_knowledgebase_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chataudioattachment',
            name='audio_file',
            field=models.FileField(max_length=500, upload_to=ai_engine.models._chat_audio_upload),
        ),
    ]
