# Generated by Django 4.2.29 on 2026-05-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0012_compliancecheckresult'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='compliancecheckresult',
            new_name='ai_engine_c_target__615408_idx',
            old_name='ai_engine_co_target__d779ca_idx',
        ),
    ]
