# Generated by Django 4.2.29 on 2026-05-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_ai', '0003_wordeditjob_mcp_contract_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordeditjob',
            name='edit_mode',
            field=models.CharField(default='direct_addin_mcp', max_length=32),
        ),
    ]
