# Generated by Django 4.2.29 on 2026-05-13 12:36

from django.db import migrations, models
import django.db.models.deletion
import word_ai.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_seed_default_company_memberships'),
        ('word_ai', '0004_alter_wordeditjob_edit_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordeditjob',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_ai_jobs', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='wordeditjob',
            name='artifact_file',
            field=models.FileField(blank=True, null=True, upload_to=word_ai.models._word_ai_artifact_upload),
        ),
    ]
