# Generated by Django 4.2.29 on 2026-05-13 12:39

from django.db import migrations, models
import word_ai.models


class Migration(migrations.Migration):

    dependencies = [
        ('word_ai', '0005_wordeditjob_company_alter_wordeditjob_artifact_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordeditjob',
            name='artifact_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=word_ai.models._word_ai_artifact_upload),
        ),
    ]
