# Generated by Django 4.2.29 on 2026-05-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0009_prompt_usage_scope_and_more'),
        ('word_ai', '0006_alter_wordeditjob_artifact_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordeditjob',
            name='applied_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_ai_jobs', to='prompts.prompt'),
        ),
    ]
