# Generated by Django 4.2.28 on 2026-03-01 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: initial).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên mẫu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('content', models.TextField(verbose_name='Nội dung mẫu')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Chia sẻ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mẫu văn bản',
                'verbose_name_plural': 'Mẫu văn bản',
                'ordering': ['-updated_at'],
            },
        ),
    ]
