# Generated by Django 4.2.28 on 2026-03-01 05:21

from django.db import migrations, models


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: documenttemplate docx file and more).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='template_docx/', verbose_name='File DOCX gốc'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Nhập thủ công'), ('docx', 'Upload file DOCX')], default='manual', max_length=10, verbose_name='Loại nguồn'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='content',
            field=models.TextField(verbose_name='Nội dung mẫu (text)'),
        ),
    ]
