# Generated by Django 4.2.28 on 2026-03-04 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: pending template assignment).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_usergroup'),
        ('document_templates', '0005_template_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatepermission',
            name='can_approve',
            field=models.BooleanField(default=False, verbose_name='Duyệt mẫu'),
        ),
        migrations.AlterField(
            model_name='templatepermission',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='Sửa nội dung'),
        ),
        migrations.CreateModel(
            name='PendingTemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, verbose_name='Tên mẫu (từ Excel)')),
                ('assign_type', models.CharField(choices=[('group', 'Nhóm'), ('private', 'Riêng tư')], max_length=10, verbose_name='Loại phân quyền')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_assignments', to='document_templates.documenttemplate', verbose_name='Mẫu đã áp dụng')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_template_assignments', to='accounts.usergroup', verbose_name='Nhóm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_template_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Chờ phân quyền mẫu',
                'verbose_name_plural': 'Chờ phân quyền mẫu',
            },
        ),
    ]
