# Generated by Django 6.0.3 on 2026-03-14 20:00

from django.db import migrations, models


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: alter documenttemplate end date and more).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0009_rename_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc hiệu lực'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='notes',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ghi chú'),
        ),
    ]
