# Generated by Django 6.0.3 on 2026-03-14 23:05

from django.db import migrations


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: merge 20260315 0605).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0009_templateversion_is_hidden'),
        ('document_templates', '0010_alter_documenttemplate_end_date_and_more'),
    ]

    operations = [
    ]
