# Generated by Django 6.0.3 on 2026-04-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0012_documenttemplate_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ duyệt'), ('pending_leader', 'Chờ trưởng nhóm duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
