# Generated by Django 4.2.29 on 2026-04-12 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_templates', '0014_templateaudiencemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateReviewNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Duyet'), ('reject', 'Tu choi')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_review_notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_review_notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_notifications', to='document_templates.documenttemplate')),
            ],
            options={
                'verbose_name': 'Thong bao duyet mau',
                'verbose_name_plural': 'Thong bao duyet mau',
                'ordering': ['-created_at'],
            },
        ),
    ]
