# Generated by Django 4.2.29 on 2026-05-13 12:36

from django.db import migrations, models
import django.db.models.deletion
import document_templates.models


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: documenttemplate company templatecategory company and more).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_seed_default_company_memberships'),
        ('document_templates', '0016_documenttemplate_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_categories', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to=document_templates.models._template_docx_upload, verbose_name='File DOCX gốc'),
        ),
        migrations.AlterField(
            model_name='templatecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='templateversion',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to=document_templates.models._template_version_docx_upload, verbose_name='File DOCX phiên bản'),
        ),
        migrations.AddConstraint(
            model_name='templatecategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_template_category_company_name'),
        ),
    ]
