# Generated by Django 4.2.29 on 2026-05-13 12:39

from django.db import migrations, models
import document_templates.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0017_documenttemplate_company_templatecategory_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='docx_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=document_templates.models._template_docx_upload, verbose_name='File DOCX gốc'),
        ),
        migrations.AlterField(
            model_name='templateversion',
            name='docx_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=document_templates.models._template_version_docx_upload, verbose_name='File DOCX phiên bản'),
        ),
    ]
