# Generated by Django 4.2.29 on 2026-05-16 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import document_templates.manual_edit_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_userprofile_is_platform_admin_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_templates', '0018_alter_documenttemplate_docx_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateManualEditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('saving', 'Saving'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='created', max_length=16)),
                ('provider', models.CharField(default='collabora', max_length=32)),
                ('access_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('wopi_file_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('working_copy_file', models.FileField(blank=True, max_length=500, null=True, upload_to=document_templates.manual_edit_models._template_manual_edit_working_copy_upload_to)),
                ('working_copy_updated_at', models.DateTimeField(blank=True, null=True)),
                ('base_version_label', models.CharField(default='1.0', max_length=20)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('lock_token', models.CharField(blank=True, max_length=255)),
                ('lock_token_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_manual_edit_sessions', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_manual_edit_sessions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_edit_sessions', to='document_templates.documenttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateManualEditSessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='info', max_length=16)),
                ('step', models.CharField(blank=True, max_length=64)),
                ('session_status', models.CharField(blank=True, max_length=16)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='document_templates.templatemanualeditsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
