# Generated by Django 4.2.29 on 2026-05-19 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: documenttemplate peer share approved at and more).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_templates', '0019_templatemanualeditsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='peer_share_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='peer_share_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_approved_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='peer_share_approver_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='peer_share_status',
            field=models.CharField(choices=[('none', 'Không chia sẻ'), ('pending_leader', 'Chờ trưởng nhóm duyệt'), ('active', 'Đã kích hoạt'), ('rejected', 'Bị từ chối')], db_index=True, default='none', max_length=20, verbose_name='Trạng thái chia sẻ đồng nghiệp'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='peer_share_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templateaudiencemember',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_audience_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
