# Generated by Django 4.2.29 on 2026-05-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0020_documenttemplate_peer_share_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateaudiencemember',
            name='permission_level',
            field=models.CharField(choices=[('view', 'Chi xem'), ('edit', 'Xem & sua'), ('delete', 'Toan quyen')], default='view', max_length=8),
        ),
    ]
