# Generated by Django 4.2.29 on 2026-06-09 14:24

from django.db import migrations, models


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: templatemanualeditsession post message origin).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0021_templateaudiencemember_permission_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemanualeditsession',
            name='post_message_origin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
