# Generated by Django 4.2.28 on 2026-03-01 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_config_level', models.CharField(choices=[('basic', 'Basic (chỉ xem)'), ('standard', 'Standard (chỉnh temperature & results)'), ('advanced', 'Advanced (chỉnh tất cả)')], default='basic', max_length=20)),
                ('ai_model', models.CharField(default='llama3:8b', max_length=100)),
                ('ai_temperature', models.FloatField(default=0.0)),
                ('ai_max_results', models.IntegerField(default=3)),
                ('embedding_model', models.CharField(default='mxbai-embed-large', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
