# Generated by Django 4.2.28 on 2026-03-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chuc_danh',
            field=models.CharField(blank=True, max_length=150, verbose_name='Chức danh'),
        ),
    ]
