# Generated by Django 4.2.29 on 2026-04-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_departmentmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dia chi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=20, verbose_name='So dien thoai'),
        ),
    ]
