# Generated by Django 6.0.3 on 2026-04-27 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_globalaiconfig_ai_model_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'PhÃƒÂ²ng ban', 'verbose_name_plural': 'PhÃƒÂ²ng ban'},
        ),
        migrations.AlterModelOptions(
            name='globalaiconfig',
            options={'verbose_name': 'CÃ¡ÂºÂ¥u hÃƒÂ¬nh AI toÃƒÂ\xa0n cÃ¡Â»Â¥c'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['name'], 'verbose_name': 'NhÃƒÂ³m ngÃ†Â°Ã¡Â»Â\x9di dÃƒÂ¹ng', 'verbose_name_plural': 'NhÃƒÂ³m ngÃ†Â°Ã¡Â»Â\x9di dÃƒÂ¹ng'},
        ),
        migrations.AlterModelOptions(
            name='usergroupmembership',
            options={'verbose_name': 'ThÃƒÂ\xa0nh viÃƒÂªn nhÃƒÂ³m', 'verbose_name_plural': 'ThÃƒÂ\xa0nh viÃƒÂªn nhÃƒÂ³m'},
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='MÃƒÂ£ phÃƒÂ²ng ban'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='MÃƒÂ´ tÃ¡ÂºÂ£'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='TrÃ†Â°Ã¡Â»Å¸ng phÃƒÂ²ng'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='TÃƒÂªn phÃƒÂ²ng ban'),
        ),
        migrations.AlterField(
            model_name='globalaiconfig',
            name='ai_max_results',
            field=models.IntegerField(default=6, verbose_name='SÃ¡Â»â€˜ kÃ¡ÂºÂ¿t quÃ¡ÂºÂ£ tÃ¡Â»â€˜i Ã„â€˜a'),
        ),
        migrations.AlterField(
            model_name='globalaiconfig',
            name='company_context',
            field=models.TextField(blank=True, verbose_name='NgÃ¡Â»Â¯ cÃ¡ÂºÂ£nh cÃƒÂ´ng ty'),
        ),
        migrations.AlterField(
            model_name='globalaiconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='CÃ¡ÂºÂ\xadp nhÃ¡ÂºÂ\xadt bÃ¡Â»Å¸i'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='NgÃ†Â°Ã¡Â»Â\x9di tÃ¡ÂºÂ¡o'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='MÃƒÂ´ tÃ¡ÂºÂ£'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='TÃƒÂªn nhÃƒÂ³m'),
        ),
        migrations.AlterField(
            model_name='usergroupmembership',
            name='role',
            field=models.CharField(choices=[('member', 'ThÃƒÂ\xa0nh viÃƒÂªn'), ('leader', 'TrÃ†Â°Ã¡Â»Å¸ng nhÃƒÂ³m')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cccd',
            field=models.CharField(blank=True, max_length=20, verbose_name='SÃ¡Â»â€˜ CCCD'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chuc_danh',
            field=models.CharField(blank=True, max_length=150, verbose_name='ChÃ¡Â»Â©c danh'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ma_nhan_vien',
            field=models.CharField(blank=True, max_length=50, verbose_name='MÃƒÂ£ nhÃƒÂ¢n viÃƒÂªn'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True, verbose_name='NgÃƒÂ\xa0y sinh'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='so_yeu_ly_lich',
            field=models.TextField(blank=True, verbose_name='SÃ†Â¡ yÃ¡ÂºÂ¿u lÃƒÂ½ lÃ¡Â»â€¹ch'),
        ),
    ]
