# Generated by Django 4.2.29 on 2026-05-13 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_alter_department_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('locked', 'Locked'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('company_context', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(default='kimi-k2.6:cloud', max_length=100)),
                ('ocr_model', models.CharField(default='qwen3-vl:4b', max_length=100)),
                ('ai_temperature', models.FloatField(default=0.0)),
                ('ai_max_results', models.IntegerField(default=6)),
                ('embedding_model', models.CharField(default='mxbai-embed-large', max_length=100)),
                ('company_context', models.TextField(blank=True)),
                ('ai_internet_results', models.IntegerField(default=3)),
                ('ai_search_engine', models.CharField(default='thuvienphapluat', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company__name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(default='excel', max_length=20)),
                ('status', models.CharField(default='previewed', max_length=20)),
                ('preview_payload', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('commit_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_username', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('company_admin', 'Company admin'), ('company_user', 'Company user')], default='company_user', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['company__name', 'local_username'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Phong ban', 'verbose_name_plural': 'Phong ban'},
        ),
        migrations.AlterModelOptions(
            name='globalaiconfig',
            options={'verbose_name': 'Cau hinh AI toan cuc'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['name'], 'verbose_name': 'Nhom nguoi dung', 'verbose_name_plural': 'Nhom nguoi dung'},
        ),
        migrations.AlterModelOptions(
            name='usergroupmembership',
            options={'verbose_name': 'Thanh vien nhom', 'verbose_name_plural': 'Thanh vien nhom'},
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tuoi'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Ma phong ban'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mo ta'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Truong phong'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ten phong ban'),
        ),
        migrations.AlterField(
            model_name='globalaiconfig',
            name='ai_max_results',
            field=models.IntegerField(default=6, verbose_name='So ket qua toi da'),
        ),
        migrations.AlterField(
            model_name='globalaiconfig',
            name='company_context',
            field=models.TextField(blank=True, verbose_name='Ngu canh cong ty'),
        ),
        migrations.AlterField(
            model_name='globalaiconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cap nhat boi'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi tao'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mo ta'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ten nhom'),
        ),
        migrations.AlterField(
            model_name='usergroupmembership',
            name='role',
            field=models.CharField(choices=[('member', 'Thanh vien'), ('leader', 'Truong nhom')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cccd',
            field=models.CharField(blank=True, max_length=20, verbose_name='So CCCD'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chuc_danh',
            field=models.CharField(blank=True, max_length=150, verbose_name='Chuc danh'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ma_nhan_vien',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ma nhan vien'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngay sinh'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='so_yeu_ly_lich',
            field=models.TextField(blank=True, verbose_name='So yeu ly lich'),
        ),
        migrations.AddField(
            model_name='companyusermembership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companyusermembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyposition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companyimportbatch',
            name='target_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companyimportbatch',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyaiconfig',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='companyaiconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_company_ai_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.company'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_department_company_name'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_department_company_code'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_user_group_company_name'),
        ),
        migrations.AddConstraint(
            model_name='companyusermembership',
            constraint=models.UniqueConstraint(fields=('company', 'local_username'), name='uniq_company_local_username'),
        ),
        migrations.AddConstraint(
            model_name='companyposition',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_company_position_code'),
        ),
        migrations.AddConstraint(
            model_name='companyposition',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_company_position_name'),
        ),
    ]
