# Generated by Django 4.2.29 on 2026-05-13 14:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_seed_default_company_memberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=accounts.models._avatar_upload),
        ),
    ]
