# Generated by Django 4.2.29 on 2026-05-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_useralias'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaiconfig',
            name='chat_ai_model',
            field=models.CharField(default='kimi-k2.6:cloud', max_length=100),
        ),
        migrations.AddField(
            model_name='globalaiconfig',
            name='chat_ai_model',
            field=models.CharField(default='kimi-k2.6:cloud', help_text='Model dung rieng cho tinh nang Tro ly chat (text + voice). De trong de dung Model AI mac dinh.', max_length=100, verbose_name='Model Chat AI'),
        ),
    ]
