# Generated by Django 4.2.28 on 2026-03-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/', verbose_name='File DOCX đã tạo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, verbose_name='Nội dung (text)'),
        ),
    ]
