# Generated by Django 6.0.3 on 2026-04-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_documentfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
