# Generated by Django 6.0.3 on 2026-04-27 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: alter document options and more).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_department_options_and_more'),
        ('document_templates', '0016_documenttemplate_soft_delete'),
        ('documents', '0011_document_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Van ban', 'verbose_name_plural': 'Van ban'},
        ),
        migrations.AlterModelOptions(
            name='documentnumberconfig',
            options={'verbose_name': 'Cau hinh ma so van ban', 'verbose_name_plural': 'Cau hinh ma so van ban'},
        ),
        migrations.AlterModelOptions(
            name='documentversion',
            options={'ordering': ['-version_number'], 'verbose_name': 'Phien ban van ban', 'verbose_name_plural': 'Phien ban van ban'},
        ),
        migrations.AlterField(
            model_name='document',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngay luu tru'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='document_templates.templatecategory', verbose_name='Danh muc'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, verbose_name='Noi dung (text)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.department', verbose_name='Phong ban'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ma so van ban'),
        ),
        migrations.AlterField(
            model_name='document',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounts.usergroup', verbose_name='Nhom'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Da luu tru'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chu'),
        ),
        migrations.AlterField(
            model_name='document',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/', verbose_name='File DOCX da tao'),
        ),
        migrations.AlterField(
            model_name='document',
            name='share_status',
            field=models.CharField(choices=[('active', 'Dang hoat dong'), ('pending_leader', 'Cho truong nhom duyet'), ('pending_admin', 'Cho admin duyet'), ('rejected', 'Bi tu choi')], default='active', max_length=20, verbose_name='Trang thai chia se'),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('generated', 'Tao tu server'), ('uploaded', 'Upload')], default='generated', max_length=20, verbose_name='Nguon tao'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Nhap'), ('final', 'Chinh thuc'), ('archived', 'Luu tru')], default='draft', max_length=20, verbose_name='Trang thai'),
        ),
        migrations.AlterField(
            model_name='document',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='document_templates.documenttemplate', verbose_name='Mau'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tieu de'),
        ),
        migrations.AlterField(
            model_name='document',
            name='version_number',
            field=models.IntegerField(default=1, verbose_name='Phien ban'),
        ),
        migrations.AlterField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('private', 'Rieng tu'), ('group', 'Nhom'), ('public', 'Cong khai')], default='private', max_length=10, verbose_name='Pham vi hien thi'),
        ),
        migrations.AlterField(
            model_name='documentnumberconfig',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_templates.templatecategory', verbose_name='Danh muc'),
        ),
        migrations.AlterField(
            model_name='documentnumberconfig',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_configs', to='accounts.department', verbose_name='Phong ban'),
        ),
        migrations.AlterField(
            model_name='documentnumberconfig',
            name='format_str',
            field=models.CharField(default='{prefix}-{number:04d}/{year}', max_length=100, verbose_name='Dinh dang ma so'),
        ),
        migrations.AlterField(
            model_name='documentnumberconfig',
            name='last_number',
            field=models.IntegerField(default=0, verbose_name='So cuoi'),
        ),
        migrations.AlterField(
            model_name='documentnumberconfig',
            name='prefix',
            field=models.CharField(max_length=20, verbose_name='Tien to'),
        ),
        migrations.AlterField(
            model_name='documentnumberconfig',
            name='year',
            field=models.IntegerField(verbose_name='Nam'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='change_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ghi chu thay doi'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='content',
            field=models.TextField(blank=True, verbose_name='Noi dung'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_versions', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi tao'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Van ban'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='An'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='variables_used',
            field=models.JSONField(blank=True, default=dict, verbose_name='Bien da dung'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='version_number',
            field=models.IntegerField(default=1, verbose_name='So phien ban'),
        ),
    ]
