# Generated by Django 4.2.29 on 2026-05-12 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.manual_edit_models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0012_alter_document_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentManualEditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('saving', 'Saving'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='created', max_length=16)),
                ('provider', models.CharField(default='collabora', max_length=32)),
                ('access_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('wopi_file_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('working_copy_file', models.FileField(blank=True, null=True, upload_to=documents.manual_edit_models._manual_edit_working_copy_upload_to)),
                ('base_version_number', models.IntegerField(default=1)),
                ('lock_token', models.CharField(blank=True, max_length=255)),
                ('lock_token_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committed_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_edit_source_sessions', to='documents.documentversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_manual_edit_sessions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_edit_sessions', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentManualEditSessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='info', max_length=16)),
                ('step', models.CharField(blank=True, max_length=64)),
                ('session_status', models.CharField(blank=True, max_length=16)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='documents.documentmanualeditsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
