# Generated by Django 4.2.29 on 2026-05-13 08:05

from django.db import migrations, models


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: documentmanualeditsession working copy updated at).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_documentmanualeditsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmanualeditsession',
            name='working_copy_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
