# Generated by Django 4.2.29 on 2026-05-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_documentmanualeditsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmanualeditsession',
            name='working_copy_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
