# Generated by Django 4.2.29 on 2026-05-13 12:36

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_seed_default_company_memberships'),
        ('documents', '0014_documentmanualeditsession_working_copy_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='documentmanualeditsession',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_edit_sessions', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='document',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models._document_output_upload, verbose_name='File DOCX da tao'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models._document_version_output_upload, verbose_name='File DOCX'),
        ),
    ]
