# Generated by Django 4.2.29 on 2026-05-13 12:39

from django.db import migrations, models
import documents.manual_edit_models
import documents.models


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: alter document output file and more).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_document_company_documentmanualeditsession_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='output_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=documents.models._document_output_upload, verbose_name='File DOCX da tao'),
        ),
        migrations.AlterField(
            model_name='documentmanualeditsession',
            name='working_copy_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=documents.manual_edit_models._manual_edit_working_copy_upload_to),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='output_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=documents.models._document_version_output_upload, verbose_name='File DOCX'),
        ),
    ]
