# Generated by Django 4.2.29 on 2026-05-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_seed_default_company_memberships'),
        ('documents', '0016_alter_document_output_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmailboxentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_entries', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='documentmailboxthread',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_threads', to='accounts.company'),
        ),
    ]
