# Generated by Django 4.2.29 on 2026-05-18 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0006_prompt_original_raw_text_and_more'),
        ('documents', '0017_documentmailboxentry_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='applied_prompt_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='Snapshot prompt khi sinh'),
        ),
        migrations.AddField(
            model_name='document',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_using', to='prompts.prompt', verbose_name='Prompt da ap dung'),
        ),
    ]
