# Generated by Django 4.2.29 on 2026-05-21 16:47

from django.db import migrations, models


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: documentaudiencemember permission level).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_document_peer_share_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaudiencemember',
            name='permission_level',
            field=models.CharField(choices=[('view', 'Chi xem'), ('edit', 'Xem & sua'), ('delete', 'Toan quyen')], default='view', max_length=8),
        ),
    ]
