# Generated by Django 4.2.29 on 2026-05-20 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITaskProgress',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('doc_create', 'Sinh văn bản từ mẫu'), ('prefill_profile', 'Điền từ hồ sơ'), ('prefill_company', 'Điền từ ngữ cảnh công ty'), ('extract_pdf', 'Trích xuất PDF'), ('extract_image', 'Trích xuất ảnh/camera'), ('summarize', 'Tóm tắt văn bản'), ('chat', 'Chat AI'), ('voice', 'Voice AI')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Chờ chạy'), ('running', 'Đang chạy'), ('completed', 'Hoàn tất'), ('failed', 'Thất bại'), ('cancelled', 'Đã dừng')], db_index=True, default='queued', max_length=16)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('progress_stage', models.CharField(blank=True, max_length=64)),
                ('progress_detail', models.CharField(blank=True, max_length=255)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('cancel_mode', models.CharField(choices=[('soft', 'Soft (cooperative)'), ('hard', 'Hard (abort connection)')], default='soft', max_length=8)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('streaming_chunks', models.JSONField(blank=True, default=list)),
                ('related_entity_type', models.CharField(blank=True, max_length=32)),
                ('related_entity_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Task Progress',
                'verbose_name_plural': 'AI Task Progress',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_tasks_ai_user_id_9b8c1a_idx'), models.Index(fields=['status', '-created_at'], name='ai_tasks_ai_status_0d608a_idx')],
            },
        ),
    ]
