# Generated by Django 4.2.29 on 2026-05-21 16:36

import ai_tasks.models
from django.db import migrations, models


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: aitaskprogress client request id and more).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này vào database.
class Migration(migrations.Migration):

    dependencies = [
        ('ai_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitaskprogress',
            name='client_request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aitaskprogress',
            name='deeplink',
            field=models.CharField(blank=True, default='', max_length=512, validators=[ai_tasks.models.validate_deeplink]),
        ),
        migrations.AddField(
            model_name='aitaskprogress',
            name='title_summary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='aitaskprogress',
            name='task_type',
            field=models.CharField(choices=[('doc_create', 'Sinh văn bản từ mẫu'), ('prefill_profile', 'Điền từ hồ sơ'), ('prefill_company', 'Điền từ ngữ cảnh công ty'), ('extract_pdf', 'Trích xuất PDF'), ('extract_image', 'Trích xuất ảnh/camera'), ('summarize', 'Tóm tắt văn bản'), ('chat', 'Chat AI'), ('voice', 'Voice AI'), ('voice_chat', 'Voice chat background'), ('bulk_template_upload', 'Bulk upload biểu mẫu'), ('document_summary', 'Tóm tắt văn bản nền'), ('compliance_check', 'Kiểm tra tuân thủ'), ('word_ai_edit', 'Word AI edit'), ('company_backup_export', 'Xuất backup công ty')], db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='aitaskprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__gt', '')), fields=('user', 'client_request_id'), name='uniq_user_client_request'),
        ),
    ]
