# Generated by Django 4.2.28 on 2026-03-05 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: prompt visibility).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_usergroup'),
        ('prompts', '0003_rename_content_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_prompts', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='approver_note',
            field=models.TextField(blank=True, verbose_name='Ghi chú duyệt'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='accounts.usergroup', verbose_name='Nhóm'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='status',
            field=models.CharField(choices=[('approved', 'Đã duyệt'), ('pending', 'Chờ admin duyệt'), ('pending_leader', 'Chờ trưởng nhóm duyệt'), ('rejected', 'Bị từ chối')], default='approved', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='visibility',
            field=models.CharField(choices=[('private', 'Riêng tư'), ('group', 'Nhóm'), ('public', 'Công khai')], default='private', max_length=10, verbose_name='Phạm vi'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='Chia sẻ (legacy)'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='rules_content',
            field=models.TextField(blank=True, help_text='Ghi đè phần QUY TẮC trong tạo văn bản. Ví dụ: "Tuyệt đối không tự điền thông tin thiếu, hãy ghi [chưa cung cấp]."', verbose_name='Suy luận (In-Context Rules)'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='system_content',
            field=models.TextField(blank=True, help_text='Thay thế toàn bộ danh tính gốc của AI. Ví dụ: "Bạn là trợ lý pháp chế của tập đoàn ABC. Luôn trả lời bằng văn phong trang trọng."', verbose_name='Hệ tư tưởng (System Ideology)'),
        ),
    ]
