# Generated by Django 4.2.29 on 2026-05-18 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prompts', '0005_alter_prompt_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='original_raw_text',
            field=models.TextField(blank=True, verbose_name='Văn bản gốc (trước sanitize)'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='original_raw_text_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Hash văn bản gốc'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='safety_flags',
            field=models.JSONField(blank=True, default=list, verbose_name='Cờ rủi ro'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='safety_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm rủi ro'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='source',
            field=models.CharField(choices=[('curated', 'Curated'), ('user_inline', 'User inline'), ('imported', 'Imported')], db_index=True, default='curated', max_length=20, verbose_name='Nguồn'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lần dùng'),
        ),
        migrations.CreateModel(
            name='PromptInjectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_input', models.TextField(blank=True)),
                ('sanitized_input', models.TextField(blank=True)),
                ('layer', models.CharField(choices=[('L1_limit', 'L1 - Hard limit'), ('L2_regex', 'L2 - Sanitize regex'), ('L3_wrap', 'L3 - XML wrapping'), ('L4_heuristic', 'L4 - Heuristic'), ('L5_llm', 'L5 - LLM classifier'), ('L6_output', 'L6 - Output validation')], db_index=True, max_length=20)),
                ('verdict', models.CharField(choices=[('allow', 'Allow'), ('redact', 'Redact'), ('block', 'Block'), ('escalate', 'Escalate')], db_index=True, max_length=16)),
                ('score', models.FloatField(default=0.0)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('llm_classifier_response', models.TextField(blank=True)),
                ('latency_ms', models.IntegerField(default=0)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('incident_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injection_logs', to='prompts.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_injection_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt injection log',
                'verbose_name_plural': 'Prompt injection logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='prompts_pro_user_id_5c77ea_idx'), models.Index(fields=['verdict', '-created_at'], name='prompts_pro_verdict_3ccb6b_idx')],
            },
        ),
    ]
