# Generated by Django 4.2.29 on 2026-05-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0006_prompt_original_raw_text_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prompt',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='uniq_prompt_owner_title'),
        ),
    ]
