# Generated by Django 4.2.29 on 2026-05-19 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: prompt peer share approved at and more).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prompts', '0007_prompt_uniq_prompt_owner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='peer_share_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='peer_share_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_approved_prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prompt',
            name='peer_share_approver_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='peer_share_status',
            field=models.CharField(choices=[('none', 'Không chia sẻ'), ('pending_leader', 'Chờ trưởng nhóm duyệt'), ('active', 'Đã kích hoạt'), ('rejected', 'Bị từ chối')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='prompt',
            name='peer_share_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PromptAudienceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_audience_added', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_members', to='prompts.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_audience_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Người được chia sẻ prompt',
                'verbose_name_plural': 'Người được chia sẻ prompt',
                'indexes': [models.Index(fields=['prompt', 'user'], name='prompts_pro_prompt__38617f_idx'), models.Index(fields=['user', '-created_at'], name='prompts_pro_user_id_8a8d65_idx')],
                'unique_together': {('prompt', 'user')},
            },
        ),
    ]
