# Generated by Django 4.2.29 on 2026-05-21 16:47

import django.contrib.postgres.fields
from django.db import migrations, models
import prompts.models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0008_prompt_peer_share_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='usage_scope',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=prompts.models.default_prompt_usage_scopes, size=None, verbose_name='Phạm vi sử dụng'),
        ),
        migrations.AddField(
            model_name='promptaudiencemember',
            name='permission_level',
            field=models.CharField(choices=[('view', 'Chi xem'), ('edit', 'Xem & sua'), ('delete', 'Toan quyen')], default='view', max_length=8),
        ),
    ]
