# Generated by Django 4.2.29 on 2026-05-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_seed_default_company_memberships'),
        ('signing', '0004_rename_internal_approval_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedpdfdocument',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_pdf_records', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='signingsystemconfig',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_config', to='accounts.company'),
        ),
    ]
