# Generated by Django 4.2.29 on 2026-05-13 12:39

from django.db import migrations, models
import signing.models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0005_signedpdfdocument_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedpdfdocument',
            name='signed_pdf_file',
            field=models.FileField(max_length=500, upload_to=signing.models._signed_pdf_upload),
        ),
        migrations.AlterField(
            model_name='signingpacket',
            name='pdf_snapshot',
            field=models.FileField(max_length=500, upload_to=signing.models._signing_snapshot_upload, verbose_name='PDF snapshot ban dau'),
        ),
        migrations.AlterField(
            model_name='signingpacket',
            name='working_pdf',
            field=models.FileField(max_length=500, upload_to=signing.models._signing_working_upload, verbose_name='PDF dang duoc ky'),
        ),
    ]
