# Generated by Django 4.2.29 on 2026-05-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_seed_default_company_memberships'),
        ('signing', '0006_alter_signedpdfdocument_signed_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingpacket',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_packets', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='signingproposal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_proposals', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='signingtask',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_tasks', to='accounts.company'),
        ),
    ]
