# Generated by Django 4.2.29 on 2026-05-16 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_useralias'),
        ('ai_engine', '0011_alter_chataudioattachment_audio_file'),
        ('documents', '0017_documentmailboxentry_company_and_more'),
        ('signing', '0007_signingpacket_company_signingproposal_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantQuickSignPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_version_number', models.PositiveIntegerField(default=1)),
                ('recipient_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('blocked', 'Blocked'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='ready', max_length=16)),
                ('signature_mode', models.CharField(choices=[('internal_approval', 'Internal approval confirmation'), ('pdf_pkcs7', 'Embedded PDF CMS/PKCS#7')], default='internal_approval', max_length=32)),
                ('requires_reauth_password', models.BooleanField(default=True)),
                ('credential_required', models.BooleanField(default=False)),
                ('can_sign_now', models.BooleanField(default=False)),
                ('already_signed', models.BooleanField(default=False)),
                ('blocking_code', models.CharField(blank=True, max_length=64)),
                ('blocking_reason', models.TextField(blank=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error_message', models.TextField(blank=True)),
                ('forward_note', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_quick_sign_plans', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_quick_sign_plans', to='auth.user')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_quick_sign_plans', to='documents.document')),
                ('mailbox_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_quick_sign_plans', to='documents.documentmailboxthread')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_assistant_quick_sign_plans', to='auth.user')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_quick_sign_plans', to='ai_engine.chatsession')),
                ('signed_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_quick_sign_plans', to='signing.signedpdfdocument')),
                ('signing_packet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_quick_sign_plans', to='signing.signingpacket')),
                ('signing_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_quick_sign_plans', to='signing.signingtask')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
