from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class PythonSpec:
    path: str
    roots: tuple[str, ...]
    helpers: tuple[str, ...] = ()
    follow_calls: bool = True


@dataclass(frozen=True)
class FeatureSpec:
    id: int
    slug: str
    title: str
    shell: str
    nav_file: str
    nav_route: str
    nav_query: str | None
    route: str
    visibility: str
    nav_group: str
    nav_match_snippets: tuple[str, ...]
    route_match_snippets: tuple[str, ...]
    subroutes: tuple[str, ...]
    screen_files: tuple[str, ...]
    provider_files: tuple[str, ...]
    api_routes: tuple[tuple[str, str], ...]
    python_specs: tuple[PythonSpec, ...]
    related_files: tuple[str, ...]
    diagram_path: str
    sequence_steps: tuple[str, ...]


def _feature(
    *,
    id: int,
    slug: str,
    title: str,
    shell: str,
    nav_file: str,
    nav_route: str,
    nav_query: str | None,
    route: str,
    visibility: str,
    nav_group: str,
    nav_match_snippets: tuple[str, ...],
    route_match_snippets: tuple[str, ...],
    subroutes: tuple[str, ...],
    screen_files: tuple[str, ...],
    provider_files: tuple[str, ...],
    api_routes: tuple[tuple[str, str], ...],
    python_specs: tuple[PythonSpec, ...],
    related_files: tuple[str, ...],
    diagram_path: str,
    sequence_steps: tuple[str, ...],
) -> FeatureSpec:
    return FeatureSpec(
        id=id,
        slug=slug,
        title=title,
        shell=shell,
        nav_file=nav_file,
        nav_route=nav_route,
        nav_query=nav_query,
        route=route,
        visibility=visibility,
        nav_group=nav_group,
        nav_match_snippets=nav_match_snippets,
        route_match_snippets=route_match_snippets,
        subroutes=subroutes,
        screen_files=screen_files,
        provider_files=provider_files,
        api_routes=api_routes,
        python_specs=python_specs,
        related_files=related_files,
        diagram_path=diagram_path,
        sequence_steps=sequence_steps,
    )


def _template_list_feature(
    *,
    id: int,
    slug: str,
    title: str,
    query: str,
    visibility: str,
    diagram_path: str,
) -> FeatureSpec:
    return _feature(
        id=id,
        slug=slug,
        title=title,
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/templates",
        nav_query=query,
        route="/templates?group=%s" % query,
        visibility=visibility,
        nav_group="Templates",
        nav_match_snippets=("'/templates'", "query: '%s'" % query),
        route_match_snippets=("path: '/templates'",),
        subroutes=("/templates/:id", "/templates/:id/edit"),
        screen_files=(
            "flutter_frontend/lib/screens/templates/template_list_screen.dart",
            "flutter_frontend/lib/screens/templates/template_detail_screen.dart",
        ),
        provider_files=("flutter_frontend/lib/providers/templates_provider.dart",),
        api_routes=(
            ("templates/", "template_list_create"),
            ("templates/<int:pk>/", "template_detail"),
            ("templates/<int:pk>/versions/", "template_versions"),
            ("templates/<int:pk>/versions/<int:ver_id>/restore/", "template_version_restore"),
            ("templates/<int:pk>/versions/<int:ver_id>/hide/", "template_version_toggle_hide"),
            ("templates/<int:pk>/versions/<int:ver_id>/diff/", "template_version_diff"),
            ("templates/<int:pk>/favorite/", "template_favorite"),
            ("templates/<int:pk>/export/", "template_export"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/templates.py",
                roots=(
                    "template_list_create",
                    "template_detail",
                    "template_versions",
                    "template_version_restore",
                    "template_version_toggle_hide",
                    "template_version_diff",
                    "template_favorite",
                    "template_export",
                ),
                helpers=("_normalize_search_terms", "_build_template_search_query", "_codex_tail_user_can_export_template"),
            ),
        ),
        related_files=(
            "api/serializers/templates.py",
            "document_templates/models.py",
            "flutter_frontend/lib/models/template.dart",
        ),
        diagram_path=diagram_path,
        sequence_steps=(
            "Nguoi dung bam muc nav `%s` tren nhom Templates." % title,
            "GoRouter dua vao `TemplateListScreen` voi `group=%s`, sau do man hinh va provider tai bo loc, danh sach mau va thong tin tong quan can dung." % query,
            "Frontend goi `GET /api/templates/` voi tham so group/pham vi de backend tra ve dung scope mau ma nav nay dai dien.",
            "Khi nguoi dung mo chi tiet, frontend di qua route `/templates/:id`, tai metadata, noi dung, version va cac hanh dong nhu favorite/export/restore neu co.",
            "Moi thao tac cap nhat tren detail se quay lai cung backend view `templates.py`, sau do list va detail duoc refresh de giao dien phan anh trang thai moi.",
        ),
    )


def _document_list_feature(
    *,
    id: int,
    slug: str,
    title: str,
    query: str,
    visibility: str,
    diagram_path: str,
) -> FeatureSpec:
    return _feature(
        id=id,
        slug=slug,
        title=title,
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/documents",
        nav_query=query,
        route="/documents?group=%s" % query,
        visibility=visibility,
        nav_group="Document management",
        nav_match_snippets=("'/documents'", "query: '%s'" % query),
        route_match_snippets=("path: '/documents'",),
        subroutes=("/documents/:id",),
        screen_files=(
            "flutter_frontend/lib/screens/documents/document_list_screen.dart",
            "flutter_frontend/lib/screens/documents/document_detail_screen.dart",
        ),
        provider_files=("flutter_frontend/lib/providers/documents_provider.dart",),
        api_routes=(
            ("documents/", "document_list_create"),
            ("documents/<int:pk>/", "document_detail_view"),
            ("documents/<int:pk>/download/", "document_download"),
            ("documents/<int:pk>/preview-pdf/", "document_preview_pdf"),
            ("documents/<int:pk>/content-html/", "document_content_html"),
            ("documents/<int:pk>/finalize/", "document_finalize"),
            ("documents/<int:pk>/archive/", "document_archive"),
            ("documents/<int:pk>/unarchive/", "document_unarchive"),
            ("documents/<int:pk>/favorite/", "document_favorite"),
            ("documents/<int:pk>/share/", "document_share"),
            ("documents/<int:pk>/versions/", "document_versions"),
            ("documents/<int:pk>/versions/<int:ver_id>/restore/", "document_version_restore"),
            ("documents/<int:pk>/versions/<int:ver_id>/hide/", "document_version_toggle_hide"),
            ("documents/<int:pk>/signing/start/", "document_signing_start"),
            ("documents/<int:pk>/signing/proposals/", "document_signing_proposal_create"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/documents.py",
                roots=(
                    "document_list_create",
                    "document_detail_view",
                    "document_download",
                    "document_preview_pdf",
                    "document_content_html",
                    "document_finalize",
                    "document_archive",
                    "document_unarchive",
                    "document_favorite",
                    "document_share",
                    "document_versions",
                    "document_version_restore",
                    "document_version_toggle_hide",
                ),
                helpers=("_normalize_search_terms", "_build_document_search_query", "_document_edit_locked_response"),
            ),
            PythonSpec(
                path="api/views/signing.py",
                roots=("document_signing_start", "document_signing_proposal_create"),
                helpers=("_resolve_signers", "_start_signing_flow_response"),
            ),
        ),
        related_files=(
            "api/serializers/documents.py",
            "documents/models.py",
            "documents/pdf_preview.py",
            "flutter_frontend/lib/models/document.dart",
            "flutter_frontend/lib/models/signing.dart",
        ),
        diagram_path=diagram_path,
        sequence_steps=(
            "Nguoi dung bam muc nav `%s` trong nhom Document management." % title,
            "GoRouter dua vao `DocumentListScreen` voi `group=%s`; provider tai danh sach van ban dung scope, bo loc va thong tin bo sung cho card/list." % query,
            "Frontend goi `GET /api/documents/` de lay danh sach; backend `documents.py` ap dung quy tac scope, tim kiem, favorite, archive va admin mode neu co.",
            "Khi nguoi dung mo 1 van ban, route `/documents/:id` tai `DocumentDetailScreen`, sau do frontend goi cac endpoint detail, preview, content html, version, share va tai file.",
            "Neu nguoi dung thuc hien cac hanh dong nghiep vu nhu finalize, archive, favorite, share hoac khoi dong signing, backend cap nhat du lieu roi frontend refresh list/detail.",
        ),
    )


FEATURES: tuple[FeatureSpec, ...] = (
    _feature(
        id=1,
        slug="dashboard",
        title="Dashboard",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/dashboard",
        nav_query=None,
        route="/dashboard",
        visibility="Moi tai khoan da dang nhap",
        nav_group="Top level",
        nav_match_snippets=("'/dashboard'",),
        route_match_snippets=("path: '/dashboard'",),
        subroutes=(),
        screen_files=("flutter_frontend/lib/screens/dashboard/dashboard_hub_screen.dart",),
        provider_files=("flutter_frontend/lib/providers/dashboard_provider.dart",),
        api_routes=(
            ("dashboard/stats/", "dashboard_stats"),
            ("dashboard/org-node-stats/<int:user_id>/", "dashboard_org_node_stats"),
            ("pending-approvals/count/", "pending_approvals_count"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/dashboard.py",
                roots=("dashboard_stats", "dashboard_org_node_stats", "pending_approvals_count"),
                helpers=(
                    "_scope_item",
                    "_person_name",
                    "_person_title",
                    "_build_org_structure",
                    "_managed_user_ids",
                    "_can_view_org_node_stats",
                ),
            ),
        ),
        related_files=(
            "flutter_frontend/lib/models/dashboard_stats.dart",
            "accounts/models.py",
            "documents/models.py",
            "document_templates/models.py",
            "ai_engine/models.py",
        ),
        diagram_path="plantuml_nav/01_dashboard_nav.puml",
        sequence_steps=(
            "Nguoi dung mo route `/dashboard` tu nav chinh.",
            "DashboardScreen doc `dashboardStatsProvider` de tai KPI tong quan, luong AI, document/template stats va activity feed.",
            "Khi nguoi dung mo node trong so do to chuc, `orgNodeStatsProvider` goi endpoint org-node-stats de lay payload chi tiet cho node duoc chon.",
            "Backend `dashboard.py` tong hop du lieu tu accounts, documents, templates va AI records, sau do tra mot payload hop nhat cho Flutter render.",
            "Badge pending approval tren dashboard duoc lay boi endpoint `pending_approvals_count` de user thay duoc nhung muc can xu ly ngay.",
        ),
    ),
    _feature(
        id=2,
        slug="ai-doc",
        title="Sinh van ban tu mau",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/ai-doc",
        nav_query=None,
        route="/ai-doc",
        visibility="Moi tai khoan da dang nhap",
        nav_group="Documents",
        nav_match_snippets=("'/ai-doc'",),
        route_match_snippets=("path: '/ai-doc'",),
        subroutes=("/ai-doc/:templateId",),
        screen_files=(
            "flutter_frontend/lib/screens/ai_doc/ai_doc_screen.dart",
            "flutter_frontend/lib/screens/ai_doc/ai_doc_fill_screen.dart",
        ),
        provider_files=("flutter_frontend/lib/providers/templates_provider.dart",),
        api_routes=(
            ("templates/", "template_list_create"),
            ("templates/<int:pk>/", "template_detail"),
            ("ai/doc/prefill-profile/", "ai_doc_prefill_profile"),
            ("ai/doc/prefill-company/", "ai_doc_prefill_company"),
            ("ai/doc/extract-pdf/", "ai_doc_extract_pdf"),
            ("ai/doc/extract-image/", "ai_doc_extract_image"),
            ("ai/doc/preview/", "ai_doc_preview"),
            ("ai/doc/create/", "ai_doc_create"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/templates.py",
                roots=("template_list_create", "template_detail"),
                helpers=("_normalize_search_terms", "_build_template_search_query"),
            ),
            PythonSpec(
                path="api/views/ai_doc.py",
                roots=(
                    "ai_doc_prefill_profile",
                    "ai_doc_prefill_company",
                    "ai_doc_extract_pdf",
                    "ai_doc_extract_image",
                    "ai_doc_preview",
                    "ai_doc_create",
                ),
                helpers=(
                    "_resolve_ocr_model",
                    "_resolve_ocr_timeout_seconds",
                    "_extract_variables_from_source_text",
                    "_extract_text_from_image_with_glm_ocr",
                    "_normalize_variable_value",
                    "_sanitize_variable_payload",
                    "_apply_prompt_to_variables",
                ),
            ),
        ),
        related_files=(
            "documents/models.py",
            "document_templates/models.py",
            "flutter_frontend/lib/models/template.dart",
            "flutter_frontend/lib/models/document.dart",
        ),
        diagram_path="plantuml_nav/02_generate_from_template_nav.puml",
        sequence_steps=(
            "Nguoi dung vao `/ai-doc` de chon template co the sinh van ban.",
            "AiDocScreen va provider tai danh sach template; sau khi chon 1 template, router mo `/ai-doc/:templateId` de vao man dien bien.",
            "AiDocFillScreen goi template detail de lay variable, sau do ho tro prefill ho so/cong ty, OCR PDF/anh, preview va tao document that.",
            "Backend `ai_doc.py` la trung tam nghiep vu cho OCR, prefill, prompt-ap-dung, preview va create; `templates.py` cung cap metadata mau dau vao.",
            "Khi create thanh cong, document moi duoc luu va user co the mo flow document detail de tiep tuc share, signing hoac download.",
        ),
    ),
    _feature(
        id=3,
        slug="document-qa",
        title="Hoi dap tai lieu",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/rag",
        nav_query=None,
        route="/rag",
        visibility="Moi tai khoan da dang nhap",
        nav_group="Documents",
        nav_match_snippets=("'/rag'",),
        route_match_snippets=("path: '/rag'",),
        subroutes=(),
        screen_files=("flutter_frontend/lib/screens/rag/rag_history_screen.dart",),
        provider_files=("flutter_frontend/lib/providers/chat_provider.dart",),
        api_routes=(
            ("ai/rag/query/", "rag_query_view"),
            ("ai/rag/sessions/", "rag_sessions"),
            ("ai/rag/sessions/<int:session_id>/messages/", "rag_session_messages"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/chat.py",
                roots=("rag_query_view", "rag_sessions", "rag_session_messages"),
            ),
        ),
        related_files=(
            "api/serializers/chat.py",
            "ai_engine/models.py",
            "documents/models.py",
            "flutter_frontend/lib/models/chat.dart",
        ),
        diagram_path="plantuml_nav/03_document_qa_nav.puml",
        sequence_steps=(
            "Nguoi dung bam muc nav `/rag` de vao man hoi dap tai lieu.",
            "RagHistoryScreen tai lich su session truoc do, sau do cho phep tao cau hoi moi va mo lai tung session cu.",
            "Moi cau hoi duoc gui len `POST /api/ai/rag/query/`; backend tim ngu can thiet trong ngu canh tai lieu va tra cau tra loi kem citation.",
            "Khi user chon lai session, frontend goi danh sach message cua session do de render lai lich su hoi dap.",
            "Toan bo luong nay chi gom feature dang co tren nav; file `rag_screen.dart` legacy khong duoc tinh vao runtime chinh.",
        ),
    ),
    _feature(
        id=4,
        slug="ai-assistant",
        title="Tro ly AI",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/chat",
        nav_query=None,
        route="/chat",
        visibility="Moi tai khoan da dang nhap",
        nav_group="Documents",
        nav_match_snippets=("'/chat'",),
        route_match_snippets=("path: '/chat'",),
        subroutes=("/chat/text", "/chat/voice", "/chat/audio", "/chat/rag-result"),
        screen_files=(
            "flutter_frontend/lib/screens/assistant/chat_ai_hub_screen.dart",
            "flutter_frontend/lib/screens/assistant/assistant_chat_screen.dart",
            "flutter_frontend/lib/screens/assistant/assistant_voice_screen.dart",
            "flutter_frontend/lib/screens/assistant/assistant_audio_library_screen.dart",
            "flutter_frontend/lib/screens/assistant/assistant_rag_result_screen.dart",
        ),
        provider_files=("flutter_frontend/lib/providers/chat_provider.dart",),
        api_routes=(
            ("assistant/turn/", "assistant_turn"),
            ("assistant/sessions/", "assistant_sessions"),
            ("assistant/sessions/<int:session_id>/messages/", "assistant_session_messages"),
            ("assistant/audio/", "assistant_audio_list"),
            ("assistant/audio/<int:audio_id>/download/", "assistant_audio_download"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/assistant.py",
                roots=(
                    "assistant_turn",
                    "assistant_sessions",
                    "assistant_session_messages",
                    "assistant_audio_list",
                    "assistant_audio_download",
                ),
                helpers=(
                    "_session_type_from_mode",
                    "_session_title_from_question",
                    "_rag_return_target",
                    "_mirror_rag_result_to_session",
                ),
            ),
        ),
        related_files=(
            "api/serializers/chat.py",
            "ai_engine/models.py",
            "flutter_frontend/lib/models/chat.dart",
            "flutter_frontend/web/voice_assistant_bridge.js",
        ),
        diagram_path="plantuml_nav/04_ai_assistant_nav.puml",
        sequence_steps=(
            "Nguoi dung bam muc nav `/chat` de vao hub chon kieu tro ly AI.",
            "ChatAiHubScreen dieu huong sang text/voice/audio/rag-result tuy thao tac ben trong cung 1 chuc nang nav.",
            "AssistantChatScreen va AssistantVoiceScreen tai session, message, gui turn moi va mo lich su hoi thoai thong qua cac endpoint `assistant/*`.",
            "Neu phan hoi can mo ra trang trich dan tai lieu, frontend tao route quay lai `/chat/rag-result` de giu user trong cung flow tro ly AI.",
            "Route `/chat/voice` khong duoc tinh la feature nav rieng, nhung van duoc liet ke o day vi la route con runtime cua feature Tro ly AI.",
        ),
    ),
    _feature(
        id=5,
        slug="signing-requests",
        title="Yeu cau ky",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/signing/tasks",
        nav_query=None,
        route="/signing/tasks",
        visibility="Moi tai khoan da dang nhap",
        nav_group="Digital signing",
        nav_match_snippets=("'/signing/tasks'",),
        route_match_snippets=("path: '/signing/tasks'",),
        subroutes=("/signing/tasks/:id",),
        screen_files=(
            "flutter_frontend/lib/screens/signing/signing_inbox_screen_modern.dart",
            "flutter_frontend/lib/screens/signing/signing_task_detail_screen_pki.dart",
        ),
        provider_files=("flutter_frontend/lib/providers/signing_summary_provider.dart",),
        api_routes=(
            ("signing/summary/", "signing_summary"),
            ("signing/tasks/", "signing_tasks"),
            ("signing/tasks/<int:task_id>/", "signing_task_detail"),
            ("signing/tasks/<int:task_id>/signature-context/", "signing_task_signature_context"),
            ("signing/tasks/<int:task_id>/preview-pdf/", "signing_task_preview_pdf"),
            ("signing/tasks/<int:task_id>/sign/", "signing_task_sign"),
            ("signing/tasks/<int:task_id>/reject/", "signing_task_reject"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/signing.py",
                roots=(
                    "signing_summary",
                    "signing_tasks",
                    "signing_task_detail",
                    "signing_task_signature_context",
                    "signing_task_preview_pdf",
                    "signing_task_sign",
                    "signing_task_reject",
                ),
                helpers=("_get_accessible_task_or_404",),
            ),
            PythonSpec(
                path="signing/permissions.py",
                roots=("get_accessible_signing_tasks", "get_signing_summary"),
            ),
            PythonSpec(
                path="signing/services.py",
                roots=("get_signature_context_for_task", "sign_task", "reject_task"),
            ),
        ),
        related_files=(
            "api/serializers/signing.py",
            "signing/models.py",
            "signing/pki.py",
            "flutter_frontend/lib/models/signing.dart",
        ),
        diagram_path="plantuml_nav/05_signing_requests_nav.puml",
        sequence_steps=(
            "Nguoi dung mo nav `/signing/tasks` de xem danh sach task ky dang cho minh xu ly.",
            "SigningInboxScreen tai summary badge va task list; khi mo 1 task, route detail tai context ky va preview PDF can ky.",
            "Backend `signing.py` ket hop `signing/permissions.py` de loc dung task ma user duoc nhin thay va duoc phep thao tac.",
            "Khi user ky hoac reject, frontend goi endpoint detail tuong ung; `signing/services.py` thuc thi validate, ky PDF, cap nhat packet/task va refresh summary.",
            "Sau khi thao tac xong, user thay duoc trang thai moi ngay trong inbox va detail.",
        ),
    ),
    _feature(
        id=6,
        slug="signed-pdfs",
        title="PDF da ky",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/signed-pdfs",
        nav_query=None,
        route="/signed-pdfs",
        visibility="Moi tai khoan da dang nhap",
        nav_group="Digital signing",
        nav_match_snippets=("'/signed-pdfs'",),
        route_match_snippets=("path: '/signed-pdfs'",),
        subroutes=("/signed-pdfs/:id",),
        screen_files=(
            "flutter_frontend/lib/screens/signing/signed_pdf_list_screen_modern.dart",
            "flutter_frontend/lib/screens/signing/signed_pdf_detail_screen_pki.dart",
        ),
        provider_files=(),
        api_routes=(
            ("signed-pdfs/", "signed_pdf_list"),
            ("signed-pdfs/<int:pk>/", "signed_pdf_detail"),
            ("signed-pdfs/<int:pk>/verify/", "signed_pdf_verify"),
            ("signed-pdfs/<int:pk>/preview-pdf/", "signed_pdf_preview_pdf"),
            ("signed-pdfs/<int:pk>/download/", "signed_pdf_download"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/signing.py",
                roots=("signed_pdf_list", "signed_pdf_detail", "signed_pdf_verify", "signed_pdf_preview_pdf", "signed_pdf_download"),
                helpers=("_get_signed_pdf_or_404",),
            ),
            PythonSpec(
                path="signing/permissions.py",
                roots=("get_accessible_signed_pdfs", "can_view_signed_pdf"),
            ),
            PythonSpec(
                path="signing/services.py",
                roots=("refresh_signed_pdf_verification", "get_signed_pdf_integrity_report", "ensure_signed_pdf_integrity"),
            ),
        ),
        related_files=(
            "api/serializers/signing.py",
            "signing/models.py",
            "flutter_frontend/lib/models/signing.dart",
        ),
        diagram_path="plantuml_nav/06_signed_pdfs_nav.puml",
        sequence_steps=(
            "Nguoi dung mo nav `/signed-pdfs` de xem danh sach PDF da ky ma minh duoc phep truy cap.",
            "Danh sach dan den detail `/signed-pdfs/:id`, tai metadata, ket qua verify, preview va duong dan download.",
            "Backend `signed_pdf_*` view loc quyen truy cap, doc file signed artifact va tra payload verification cho man detail.",
            "Neu user bam verify/download, frontend goi endpoint tuong ung; service signing kiem tra tinh toan ven cua file ky so truoc khi cho phep tai ve.",
            "Detail co the dieu huong sang mailbox lien quan neu ban PDF da ky co thread mailbox moi nhat.",
        ),
    ),
    _feature(
        id=7,
        slug="mailbox",
        title="Hom thu",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/mailbox",
        nav_query=None,
        route="/mailbox",
        visibility="Moi tai khoan da dang nhap",
        nav_group="Digital signing",
        nav_match_snippets=("'/mailbox'",),
        route_match_snippets=("path: '/mailbox'",),
        subroutes=("/mailbox/:id",),
        screen_files=(
            "flutter_frontend/lib/screens/documents/mailbox_screen_modern.dart",
            "flutter_frontend/lib/screens/documents/mailbox_detail_screen_modern.dart",
        ),
        provider_files=("flutter_frontend/lib/providers/signing_summary_provider.dart",),
        api_routes=(
            ("mailbox/", "mailbox_thread_list"),
            ("mailbox/<int:thread_id>/", "mailbox_thread_detail"),
            ("mailbox/<int:thread_id>/verify/", "mailbox_thread_verify"),
            ("mailbox/<int:thread_id>/preview-pdf/", "mailbox_thread_preview_pdf"),
            ("mailbox/entries/<int:entry_id>/sign/", "mailbox_entry_sign"),
            ("mailbox/entries/<int:entry_id>/forward/", "mailbox_entry_forward"),
            ("mailbox/entries/<int:entry_id>/complete/", "mailbox_entry_complete"),
            ("mailbox/entries/<int:entry_id>/reject/", "mailbox_entry_reject"),
            ("mailbox/entries/<int:entry_id>/verify/", "mailbox_entry_verify"),
            ("mailbox/entries/<int:entry_id>/preview-pdf/", "mailbox_entry_preview_pdf"),
            ("signing/candidates/", "signing_candidates"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/documents.py",
                roots=(
                    "mailbox_thread_list",
                    "mailbox_thread_detail",
                    "mailbox_thread_verify",
                    "mailbox_thread_preview_pdf",
                    "mailbox_entry_sign",
                    "mailbox_entry_forward",
                    "mailbox_entry_complete",
                    "mailbox_entry_reject",
                    "mailbox_entry_verify",
                    "mailbox_entry_preview_pdf",
                ),
                helpers=("_accessible_mailbox_threads", "_accessible_mailbox_entries", "_resolve_forward_recipients"),
            ),
            PythonSpec(
                path="documents/mailbox_services.py",
                roots=(
                    "forward_document",
                    "complete_mailbox_entry",
                    "reject_mailbox_entry",
                    "ensure_mailbox_entry_signing_task",
                    "mailbox_integrity_report",
                    "mailbox_thread_integrity_report",
                ),
            ),
            PythonSpec(path="api/views/signing.py", roots=("signing_candidates",)),
        ),
        related_files=(
            "api/serializers/documents.py",
            "documents/models.py",
            "signing/models.py",
            "flutter_frontend/lib/models/document.dart",
            "flutter_frontend/lib/models/signing.dart",
        ),
        diagram_path="plantuml_nav/07_mailbox_nav.puml",
        sequence_steps=(
            "Nguoi dung vao nav `/mailbox` de xem cac thread van ban dang luu chuyen trong hop thu nghiep vu.",
            "Danh sach thread mo sang `/mailbox/:id`; detail tai thread, preview PDF mailbox, verify va entry hien tai cua nguoi dung dang xem.",
            "User co the sign, forward, complete hoac reject entry; moi hanh dong goi endpoint mailbox entry tuong ung.",
            "Backend `documents.py` va `documents/mailbox_services.py` dieu phoi quy tac luan chuyen, tao task signing neu can va cap nhat status thread/entry.",
            "Sau moi thao tac, summary badge va detail mailbox duoc refresh de giao dien phan anh dung thread con cho xu ly.",
        ),
    ),
    _feature(
        id=8,
        slug="signing-delegation",
        title="Uy quyen ky so",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/signing/access",
        nav_query=None,
        route="/signing/access",
        visibility="Chi hien khi user co quyen HR delegation hoac accounting delegation",
        nav_group="Digital signing",
        nav_match_snippets=("'/signing/access'",),
        route_match_snippets=("path: '/signing/access'",),
        subroutes=(),
        screen_files=("flutter_frontend/lib/screens/signing/signing_delegation_screen.dart",),
        provider_files=("flutter_frontend/lib/providers/signing_summary_provider.dart",),
        api_routes=(
            ("signing/summary/", "signing_summary"),
            ("signing/candidates/", "signing_candidates"),
            ("signing/delegations/", "signing_delegations"),
            ("signing/delegations/<int:delegation_id>/", "signing_delegation_detail"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/signing.py",
                roots=("signing_summary", "signing_candidates", "signing_delegations", "signing_delegation_detail"),
            ),
            PythonSpec(
                path="signing/permissions.py",
                roots=("can_manage_hr_delegations", "can_manage_accounting_delegations", "get_signing_system_config"),
            ),
        ),
        related_files=(
            "api/serializers/signing.py",
            "signing/models.py",
            "flutter_frontend/lib/models/signing.dart",
        ),
        diagram_path="plantuml_nav/08_signing_delegation_nav.puml",
        sequence_steps=(
            "Nav `/signing/access` chi hien khi summary cho biet user co quyen quan ly uy quyen ky so dac thu.",
            "Man `SigningDelegationScreen` tai summary, danh sach delegation hien co va danh sach candidate hop le cho tung permission type.",
            "User co the tao delegation moi hoac xoa delegation cu; frontend goi `signing/delegations/` va `signing/delegations/:id/`.",
            "Backend `signing.py` va `signing/permissions.py` xac thuc user co dung vai tro dac biet truoc khi cho phep thay doi delegation.",
            "Khi thao tac xong, `signingSummaryProvider` bi invalidate de nav va man hinh cap nhat badge/quyen moi nhat.",
        ),
    ),
    _feature(
        id=9,
        slug="template-create",
        title="Tao mau van ban",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/templates/create",
        nav_query=None,
        route="/templates/create",
        visibility="Moi tai khoan da dang nhap",
        nav_group="Templates",
        nav_match_snippets=("'/templates/create'",),
        route_match_snippets=("path: 'create'",),
        subroutes=("/templates/create?source_url=...", "/templates/bulk-upload"),
        screen_files=(
            "flutter_frontend/lib/screens/templates/template_creation_hub_screen.dart",
            "flutter_frontend/lib/screens/templates/template_form_screen.dart",
            "flutter_frontend/lib/screens/templates/bulk_upload_screen.dart",
        ),
        provider_files=("flutter_frontend/lib/providers/templates_provider.dart",),
        api_routes=(
            ("templates/", "template_list_create"),
            ("templates/group-members/", "template_group_members"),
            ("templates/import-docx/", "template_import_docx"),
            ("templates/import-from-url/", "template_import_from_url"),
            ("templates/<int:pk>/generate-tags/", "template_generate_tags"),
            ("templates/<int:pk>/replace-docx/", "template_replace_docx"),
            ("templates/bulk/parse-excel/", "bulk_parse_excel"),
            ("templates/bulk/upload-single/", "bulk_upload_single"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/templates.py",
                roots=(
                    "template_list_create",
                    "template_group_members",
                    "template_import_docx",
                    "template_import_from_url",
                    "template_generate_tags",
                ),
            ),
            PythonSpec(
                path="api/views/bulk_upload.py",
                roots=("bulk_parse_excel", "bulk_upload_single", "template_replace_docx"),
            ),
        ),
        related_files=(
            "api/serializers/templates.py",
            "document_templates/forms.py",
            "document_templates/models.py",
            "flutter_frontend/lib/models/template.dart",
        ),
        diagram_path="plantuml_nav/09_create_template_nav.puml",
        sequence_steps=(
            "Nguoi dung bam nav `/templates/create` de vao hub tao mau.",
            "Hub cho phep tao moi, import DOCX, import tu URL, edit theo source co san hoac bulk upload.",
            "TemplateFormScreen tai group members, metadata va cac cong cu generate tags/replace docx de tao noi dung template hop le.",
            "Neu user chon bulk upload, `BulkUploadScreen` goi parse Excel va upload tung hang len backend `bulk_upload.py`.",
            "Khi template duoc tao thanh cong, no quay ve danh sach/detail template de user tiep tuc share, submit va quan ly version.",
        ),
    ),
    _template_list_feature(
        id=10,
        slug="templates-shared",
        title="Mau dung chung",
        query="system",
        visibility="Moi tai khoan da dang nhap",
        diagram_path="plantuml_nav/10_templates_shared_nav.puml",
    ),
    _template_list_feature(
        id=11,
        slug="templates-department",
        title="Mau phong ban cua toi",
        query="team",
        visibility="Moi tai khoan da dang nhap",
        diagram_path="plantuml_nav/11_templates_my_department_nav.puml",
    ),
    _template_list_feature(
        id=12,
        slug="templates-private",
        title="Mau rieng cua toi",
        query="private",
        visibility="Moi tai khoan da dang nhap",
        diagram_path="plantuml_nav/12_templates_my_private_nav.puml",
    ),
    _template_list_feature(
        id=13,
        slug="templates-favorites",
        title="Mau yeu thich",
        query="favorite",
        visibility="Moi tai khoan da dang nhap",
        diagram_path="plantuml_nav/13_templates_favorites_nav.puml",
    ),
    _template_list_feature(
        id=14,
        slug="templates-admin",
        title="Tat ca mau (Admin)",
        query="admin",
        visibility="Chi superuser",
        diagram_path="plantuml_nav/14_templates_admin_nav.puml",
    ),
    _document_list_feature(
        id=15,
        slug="documents-private",
        title="Van ban cua toi",
        query="private",
        visibility="Moi tai khoan da dang nhap",
        diagram_path="plantuml_nav/15_documents_my_nav.puml",
    ),
    _document_list_feature(
        id=16,
        slug="documents-group",
        title="Van ban chia se trong nhom",
        query="group",
        visibility="Moi tai khoan da dang nhap",
        diagram_path="plantuml_nav/16_documents_group_nav.puml",
    ),
    _document_list_feature(
        id=17,
        slug="documents-public",
        title="Van ban chia se cong khai",
        query="public",
        visibility="Moi tai khoan da dang nhap",
        diagram_path="plantuml_nav/17_documents_public_nav.puml",
    ),
    _document_list_feature(
        id=18,
        slug="documents-favorites",
        title="Van ban yeu thich",
        query="favorite",
        visibility="Moi tai khoan da dang nhap",
        diagram_path="plantuml_nav/18_documents_favorites_nav.puml",
    ),
    _document_list_feature(
        id=19,
        slug="documents-archived",
        title="Van ban da luu tru",
        query="archived",
        visibility="Moi tai khoan da dang nhap",
        diagram_path="plantuml_nav/19_documents_archived_nav.puml",
    ),
    _document_list_feature(
        id=20,
        slug="documents-admin",
        title="Tat ca van ban (Admin)",
        query="admin",
        visibility="Chi superuser",
        diagram_path="plantuml_nav/20_documents_admin_nav.puml",
    ),
    _feature(
        id=21,
        slug="trash",
        title="Thung rac",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/trash",
        nav_query=None,
        route="/trash",
        visibility="Moi tai khoan da dang nhap",
        nav_group="System",
        nav_match_snippets=("'/trash'",),
        route_match_snippets=("path: '/trash'",),
        subroutes=(),
        screen_files=("flutter_frontend/lib/screens/system/trash_screen.dart",),
        provider_files=(),
        api_routes=(
            ("trash/entries/", "trash_entries"),
            ("trash/restore/", "trash_restore"),
            ("trash/delete/", "trash_delete"),
        ),
        python_specs=(
            PythonSpec(path="api/views/trash.py", roots=("trash_entries", "trash_restore", "trash_delete")),
            PythonSpec(
                path="api/trash_services.py",
                roots=("list_trash_entries", "restore_trash_items", "permanently_delete_trash_items", "trash_counts"),
                helpers=("normalize_id_list", "mark_deleted", "restore_deleted", "purge_expired_trash"),
            ),
        ),
        related_files=(
            "flutter_frontend/lib/models/trash.dart",
            "documents/models.py",
            "document_templates/models.py",
            "ai_engine/models.py",
        ),
        diagram_path="plantuml_nav/21_trash_nav.puml",
        sequence_steps=(
            "Nguoi dung mo nav `/trash` de xem cac doi tuong da xoa mem.",
            "TrashScreen tai danh sach entry, thong ke theo loai va bo loc tim kiem.",
            "Frontend goi `trash_entries`, `trash_restore`, `trash_delete`; backend `api/trash_services.py` la noi gom va xu ly logic cho template/document/chat bi xoa.",
            "Khi user khoi phuc hoac xoa vinh vien, backend cap nhat trang thai object goc va tra lai ket qua de frontend refresh danh sach.",
            "Bao cao nay chi tinh thung rac dang co tren nav, khong gom cac flow xoa tam/cleanup noi bo khong hien cho user.",
        ),
    ),
    _feature(
        id=22,
        slug="profile",
        title="Ho so ca nhan",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/profile",
        nav_query=None,
        route="/profile",
        visibility="Moi tai khoan da dang nhap",
        nav_group="System",
        nav_match_snippets=("'/profile'",),
        route_match_snippets=("path: '/profile'",),
        subroutes=(),
        screen_files=("flutter_frontend/lib/screens/profile/profile_screen.dart",),
        provider_files=("flutter_frontend/lib/providers/auth_provider.dart",),
        api_routes=(
            ("auth/me/", "me"),
            ("auth/me/prefill-from-bio/", "prefill_from_bio"),
            ("auth/logout/", "logout_view"),
        ),
        python_specs=(
            PythonSpec(path="api/views/auth.py", roots=("me", "prefill_from_bio", "logout_view"), helpers=("_ensure_signing_credential",)),
        ),
        related_files=(
            "api/serializers/auth.py",
            "accounts/models.py",
            "accounts/forms.py",
            "flutter_frontend/lib/models/user.dart",
        ),
        diagram_path="plantuml_nav/22_profile_nav.puml",
        sequence_steps=(
            "Nguoi dung bam nav `/profile` de quan ly thong tin ca nhan.",
            "ProfileScreen tai profile hien tai, cac thong tin bo sung va cac truong co the sua hoac dung cho prefill.",
            "Frontend goi `GET/PATCH /api/auth/me/` de doc va cap nhat ho so, va goi `prefill-from-bio` khi can sinh san cac truong phu tro AI/doc.",
            "Backend `auth.py` validate user hien tai, dong bo credential signing neu can va tra lai profile moi nhat cho frontend render.",
            "Neu user logout tu vung profile, flow se quay lai trang dang nhap va xoa state dang nhap hien tai.",
        ),
    ),
    _feature(
        id=23,
        slug="pending-approvals",
        title="Yeu cau phe duyet",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/pending-approvals",
        nav_query=None,
        route="/pending-approvals",
        visibility="Chi user co `canApprovePending == true`",
        nav_group="Approvals",
        nav_match_snippets=("'/pending-approvals'",),
        route_match_snippets=("path: '/pending-approvals'",),
        subroutes=(),
        screen_files=("flutter_frontend/lib/screens/documents/pending_approvals_screen.dart",),
        provider_files=(
            "flutter_frontend/lib/providers/pending_approvals_provider.dart",
            "flutter_frontend/lib/providers/signing_summary_provider.dart",
        ),
        api_routes=(
            ("templates/pending-shares/", "template_pending_shares"),
            ("templates/<int:pk>/approve/", "template_approve"),
            ("templates/<int:pk>/reject/", "template_reject"),
            ("documents/pending-shares/", "document_pending_shares"),
            ("documents/<int:pk>/approve-share/", "document_approve_share"),
            ("pending-approvals/count/", "pending_approvals_count"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/templates.py",
                roots=("template_pending_shares", "template_approve", "template_reject"),
            ),
            PythonSpec(
                path="api/views/documents.py",
                roots=("document_pending_shares", "document_approve_share"),
            ),
            PythonSpec(path="api/views/dashboard.py", roots=("pending_approvals_count",)),
        ),
        related_files=(
            "api/serializers/documents.py",
            "api/serializers/templates.py",
            "documents/models.py",
            "document_templates/models.py",
        ),
        diagram_path="plantuml_nav/23_approval_requests_nav.puml",
        sequence_steps=(
            "Nav `/pending-approvals` chi hien khi user co quyen phe duyet template/document dang cho duyet.",
            "PendingApprovalsScreen tai du lieu dang cho tu ca template va document, sau do hien thanh cac card theo tung loai.",
            "User phe duyet hoac tu choi tung muc; frontend goi endpoint template/document tuong ung va cap nhat badge count.",
            "Backend tra lai trang thai moi, dong thoi `pending_approvals_count` duoc dung cho badge tren nav/dashboard.",
            "Chi cac flow duyet thuc su co tren nav duoc liet ke, khong mo rong sang quy trinh ky so khac.",
        ),
    ),
    _feature(
        id=24,
        slug="ai-settings",
        title="Cau hinh AI",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/admin/ai-config",
        nav_query=None,
        route="/admin/ai-config",
        visibility="Chi user co `isStaff == true`",
        nav_group="Administration",
        nav_match_snippets=("'/admin/ai-config'",),
        route_match_snippets=("path: '/admin/ai-config'",),
        subroutes=(),
        screen_files=("flutter_frontend/lib/screens/admin/ai_config_screen.dart",),
        provider_files=(),
        api_routes=(
            ("admin/ai-config/", "ai_config"),
            ("admin/ollama-models/", "ollama_models"),
            ("admin/company-context/", "company_context_read"),
        ),
        python_specs=(
            PythonSpec(path="api/views/admin_v.py", roots=("ai_config", "ollama_models", "company_context_read")),
        ),
        related_files=(
            "api/serializers/admin_s.py",
            "prompts/models.py",
            "ai_engine/models.py",
        ),
        diagram_path="plantuml_nav/24_ai_settings_nav.puml",
        sequence_steps=(
            "User staff vao nav `/admin/ai-config` de quan ly cau hinh AI he thong.",
            "AiConfigScreen tai config hien tai, danh sach model tu Ollama va phan company context duoc dung cho prompt/doc flows.",
            "Frontend goi `admin/ai-config`, `admin/ollama-models` va `admin/company-context`; backend `admin_v.py` doc/ghi cau hinh va tra danh sach model hop le.",
            "Khi user bam luu, backend cap nhat config va frontend hien thong bao thanh cong/that bai.",
            "Feature nay chi mo ta man cau hinh AI tren nav, khong bao gom route `prompts` vi route do hien khong co tren nav.",
        ),
    ),
    _feature(
        id=25,
        slug="accounts-departments-groups",
        title="Tai khoan, phong ban va nhom",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/admin",
        nav_query=None,
        route="/admin",
        visibility="Chi user co `isStaff == true`",
        nav_group="Administration",
        nav_match_snippets=("'/admin'",),
        route_match_snippets=("path: '/admin'",),
        subroutes=(),
        screen_files=("flutter_frontend/lib/screens/admin/admin_screen.dart",),
        provider_files=(),
        api_routes=(
            ("admin/users/", "user_list"),
            ("admin/users/<int:pk>/", "user_detail"),
            ("admin/groups/", "group_list"),
            ("admin/groups/<int:pk>/", "group_detail"),
            ("admin/groups/<int:pk>/members/", "group_members"),
            ("admin/groups/<int:pk>/members/<int:user_id>/", "group_member_detail"),
            ("admin/import-users/", "import_users_excel"),
            ("admin/import-users/template/", "import_users_template"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/admin_v.py",
                roots=(
                    "user_list",
                    "user_detail",
                    "group_list",
                    "group_detail",
                    "group_members",
                    "group_member_detail",
                    "import_users_excel",
                    "import_users_template",
                ),
                helpers=("_col_idx", "_cell", "_normalize_group_name", "_find_duplicate_group", "_group_usage_counts"),
            ),
        ),
        related_files=(
            "api/serializers/admin_s.py",
            "accounts/models.py",
            "accounts/forms.py",
            "flutter_frontend/lib/models/user.dart",
        ),
        diagram_path="plantuml_nav/25_accounts_departments_nav.puml",
        sequence_steps=(
            "User staff vao nav `/admin` de quan ly user, group va import du lieu nhan su.",
            "AdminScreen tai song song danh sach user va group, sau do mo cac dialog de tao/sua/xoa va quan ly thanh vien.",
            "Moi thao tac CRUD tren user/group/member map truc tiep vao cac endpoint `admin/users/*` va `admin/groups/*`.",
            "Tab import su dung `import_users_template` de tai file mau va `import_users_excel` de gui file Excel len backend parse/ap dung thay doi hang loat.",
            "Chi man admin runtime nay duoc ghi nhan; mode admin cua templates/documents la chuc nang nav khac, khong gop chung vao feature nay.",
        ),
    ),
    _feature(
        id=26,
        slug="backups",
        title="Sao luu du lieu",
        shell="app",
        nav_file="flutter_frontend/lib/widgets/shell/app_shell.dart",
        nav_route="/admin/backup",
        nav_query=None,
        route="/admin/backup",
        visibility="Chi superuser",
        nav_group="Administration",
        nav_match_snippets=("'/admin/backup'",),
        route_match_snippets=("path: '/admin/backup'",),
        subroutes=(),
        screen_files=("flutter_frontend/lib/screens/admin/backup_screen.dart",),
        provider_files=(),
        api_routes=(
            ("admin/backup/", "backup_list"),
            ("admin/backup/create/", "backup_create"),
            ("admin/backup/<str:filename>/download/", "backup_download"),
            ("admin/backup/<str:filename>/", "backup_delete"),
        ),
        python_specs=(
            PythonSpec(path="api/views/admin_v.py", roots=("backup_list", "backup_create", "backup_download", "backup_delete")),
        ),
        related_files=(
            "api/serializers/admin_s.py",
            "my_tennis_club/management/commands/reset_db.py",
            "backups",
        ),
        diagram_path="plantuml_nav/26_backups_nav.puml",
        sequence_steps=(
            "Superuser vao nav `/admin/backup` de xem file backup va tao ban sao luu moi.",
            "BackupScreen tai danh sach file, thong ke DB va cho phep tao, download, xoa backup.",
            "Frontend goi `backup_list`, `backup_create`, `backup_download`, `backup_delete`; backend `admin_v.py` thuc hien xu ly file va tra ket qua cho UI.",
            "Sau khi tao/xoa, danh sach duoc nap lai de user thay ngay artifact moi nhat.",
            "Chi chuc nang backup tren nav duoc ghi nhan; lenh reset DB chi duoc liet ke o muc file lien quan vi co tac dong cung mien nghiep vu quan tri.",
        ),
    ),
    _feature(
        id=27,
        slug="guest-generate",
        title="Guest tao van ban",
        shell="guest",
        nav_file="flutter_frontend/lib/widgets/shell/guest_shell.dart",
        nav_route="/guest",
        nav_query=None,
        route="/guest",
        visibility="Moi guest truoc dang nhap",
        nav_group="Guest documents",
        nav_match_snippets=("route: '/guest'",),
        route_match_snippets=("path: '/guest'",),
        subroutes=(),
        screen_files=("flutter_frontend/lib/screens/guest/guest_ai_screen.dart",),
        provider_files=(),
        api_routes=(
            ("guest/session/", "guest_session_info"),
            ("guest/session/cleanup/", "guest_cleanup"),
            ("guest/parse/", "guest_parse_template"),
            ("guest/parse-info/", "guest_parse_info"),
            ("guest/parse-pdf/", "guest_parse_pdf"),
            ("guest/generate/", "guest_generate"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/guest_portal_cookie.py",
                roots=(
                    "guest_session_info",
                    "guest_cleanup",
                    "guest_parse_template",
                    "guest_parse_info",
                    "guest_parse_pdf",
                    "guest_generate",
                ),
                helpers=(
                    "_ensure_guest_identity",
                    "_read_guest_meta",
                    "_write_guest_meta",
                    "_store_guest_template",
                    "_auto_detect_template_variables",
                    "_guest_document_payload",
                    "_extract_pdf_text",
                ),
            ),
        ),
        related_files=(
            "flutter_frontend/web/voice_assistant_bridge.js",
            "flutter_frontend/lib/models/document.dart",
        ),
        diagram_path="plantuml_nav/27_guest_generate_nav.puml",
        sequence_steps=(
            "Guest mo nav `/guest` de vao cong tao van ban khong can dang nhap.",
            "GuestAiScreen doc session guest, upload template, parse bien, parse thong tin/PDF va tao document tam trong pham vi cookie/session.",
            "Backend `guest_portal_cookie.py` quan ly guest identity, luu template tam, parse noi dung va sinh document dau ra.",
            "Khi document duoc tao, metadata guest duoc cap nhat de nav co the hien muc 'Van ban vua tao'.",
            "Chi 2 muc guest usable duoc bao cao; cac tile guest bi khoa tren nav khong duoc sinh ho so.",
        ),
    ),
    _feature(
        id=28,
        slug="guest-latest-document",
        title="Guest xem van ban vua tao",
        shell="guest",
        nav_file="flutter_frontend/lib/widgets/shell/guest_shell.dart",
        nav_route="/guest/document",
        nav_query=None,
        route="/guest/document",
        visibility="Chi hien khi guest da co document vua tao",
        nav_group="Guest documents",
        nav_match_snippets=("route: '/guest/document'",),
        route_match_snippets=("path: '/guest/document'",),
        subroutes=(),
        screen_files=("flutter_frontend/lib/screens/guest/guest_document_detail_screen.dart",),
        provider_files=(),
        api_routes=(
            ("guest/document/", "guest_document_detail"),
            ("guest/document/content-html/", "guest_document_content_html"),
            ("guest/document/download/", "guest_document_download"),
        ),
        python_specs=(
            PythonSpec(
                path="api/views/guest_portal_cookie.py",
                roots=("guest_document_detail", "guest_document_content_html", "guest_document_download"),
                helpers=("_guest_document_payload", "_guest_html_page"),
            ),
        ),
        related_files=("flutter_frontend/lib/models/document.dart",),
        diagram_path="plantuml_nav/28_guest_latest_document_nav.puml",
        sequence_steps=(
            "Sau khi guest tao document thanh cong, nav co the hien muc `/guest/document` de mo lai ban vua tao.",
            "GuestDocumentDetailScreen tai metadata, HTML preview va kha nang download document da sinh.",
            "Backend doc document tam theo guest session/cookie, tra payload chi tiet, HTML render va file download.",
            "Feature nay chi ton tai khi guest da co artifact moi nhat; neu khong co document, muc nav nay se khong duoc render.",
            "Khong co flow guest detail nao khac duoc them vao bao cao vi cac muc guest con lai deu dang bi khoa.",
        ),
    ),
)


FEATURE_BY_ID = {feature.id: feature for feature in FEATURES}
FEATURE_BY_SLUG = {feature.slug: feature for feature in FEATURES}
