# Generated by Django 4.2.29 on 2026-05-19 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0021_useralias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_enabled', models.BooleanField(default=True)),
                ('auto_interval_days', models.PositiveIntegerField(default=30)),
                ('backup_password_hash', models.CharField(blank=True, max_length=255)),
                ('retention_count', models.PositiveIntegerField(default=12)),
                ('last_auto_run_at', models.DateTimeField(blank=True, null=True)),
                ('notify_admin_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_settings', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Cau hinh sao luu doanh nghiep',
                'verbose_name_plural': 'Cau hinh sao luu doanh nghiep',
            },
        ),
        migrations.CreateModel(
            name='CompanyBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('manual', 'Thu cong'), ('auto', 'Tu dong')], db_index=True, max_length=10)),
                ('components', models.JSONField(blank=True, default=list)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('creating', 'Dang tao'), ('ready', 'San sang'), ('failed', 'That bai'), ('restoring', 'Dang khoi phuc'), ('restored', 'Da khoi phuc'), ('deleted', 'Da xoa')], db_index=True, default='creating', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_backups_created', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_backups_restored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ban sao luu doanh nghiep',
                'verbose_name_plural': 'Ban sao luu doanh nghiep',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='company_bac_company_e0701e_idx'), models.Index(fields=['company', 'kind', '-created_at'], name='company_bac_company_f81b14_idx')],
            },
        ),
    ]
