# Generated by Django 4.2.29 on 2026-05-19 02:42

from django.db import migrations, models


# class Migration là bước migration thay đổi cấu trúc CSDL (theo tên file: companybackup progress detail and more).
# vd: chạy "python manage.py migrate" để áp dụng thay đổi schema này.
class Migration(migrations.Migration):

    dependencies = [
        ('company_backups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybackup',
            name='progress_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companybackup',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companybackup',
            name='progress_stage',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
