# Generated by Django 4.2.29 on 2026-05-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_backups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybackup',
            name='progress_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companybackup',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companybackup',
            name='progress_stage',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
