# Generated by Django 4.2.30 on 2026-05-22 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_backfill_share_grants'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sharegrant',
            new_name='sharing_sha_content_2479db_idx',
            old_name='sharing_sha_content_d63b5e_idx',
        ),
        migrations.RenameIndex(
            model_name='sharegrant',
            new_name='sharing_sha_target__1f3869_idx',
            old_name='sharing_sha_target__22a4d8_idx',
        ),
        migrations.RenameIndex(
            model_name='sharegrant',
            new_name='sharing_sha_target__23fc08_idx',
            old_name='sharing_sha_target__f3e74c_idx',
        ),
        migrations.RenameIndex(
            model_name='sharegrant',
            new_name='sharing_sha_scope_3ed303_idx',
            old_name='sharing_sha_scope_b16291_idx',
        ),
    ]
