"""
Thuoc chuc nang nao: Bang dieu khien, Tai khoan - phong ban - nhom, Cau hinh AI, Sao luu du lieu, thong bao va ha tang route chung.
Vai tro backend: File `api/urls.py` giu hoac ho tro luong backend cho cau hinh du an, anh xa route, thong ke dashboard, quan tri du lieu nen va API chung toan he thong.
Vai tro cua no trong frontend: Cac man `/dashboard`, `/admin`, `/admin/ai-config`, `/admin/backup`, badge thong bao va shell dieu huong doc hoac chiu tac dong tu file nay.
Moi lien he voi nhung ham / source khac: Tuong tac truc tiep voi `my_tennis_club.settings`, `my_tennis_club.urls`, `api/views/dashboard.py`, `api/views/admin_v.py`, `api/views/notifications.py`, `api.views`.
Tac dung: Giu cho cac man dieu phoi cap he thong co cung nguon cau hinh, cung route va cung so lieu nen khi frontend khoi chay.
"""

from django.urls import path
from .views import (
    ai_doc,
    assistant,
    auth,
    bulk_upload,
    chat,
    company_admin,
    dashboard,
    document_summaries,
    document_manual_edit,
    documents,
    guest_portal_cookie,
    global_search,
    notifications,
    platform_companies,
    prompt_composer,
    prompts,
    compliance,
    signing,
    template_manual_edit,
    templates,
    trash,
    word_ai_jobs,
    word_ai_workers,
    admin_v,
    company_backups,
    users_search,
    templates_peer,
    documents_peer,
    prompts_peer,
    sharing as sharing_views,
    ai_tasks as ai_tasks_views,
)

app_name = 'api'

urlpatterns = [
    
    path('auth/register/', auth.register, name='register'),
    path('auth/login/', auth.login_view, name='login'),
    path('auth/logout/', auth.logout_view, name='logout'),
    path('auth/me/', auth.me, name='me'),
    path('auth/me/prefill-from-bio/', auth.prefill_from_bio, name='prefill_from_bio'),
    path('auth/social/google/', auth.social_google, name='social_google'),
    path('auth/social/facebook/', auth.social_facebook, name='social_facebook'),
    path('public/companies/suggest/', platform_companies.public_company_suggest, name='public_company_suggest'),
    path('platform/companies/', platform_companies.platform_company_list_create, name='platform_company_list_create'),
    path('platform/companies/trash/', platform_companies.platform_company_trash, name='platform_company_trash'),
    path('platform/companies/<int:pk>/', platform_companies.platform_company_detail, name='platform_company_detail'),
    path('platform/companies/<int:pk>/ai-config/', platform_companies.platform_company_ai_config, name='platform_company_ai_config'),
    path('platform/companies/<int:pk>/bootstrap-reset/', platform_companies.platform_company_bootstrap_reset, name='platform_company_bootstrap_reset'),
    path('platform/companies/<int:pk>/restore/', platform_companies.platform_company_restore, name='platform_company_restore'),
    path('platform/companies/<int:pk>/hard-delete/', platform_companies.platform_company_hard_delete, name='platform_company_hard_delete'),
    path('platform/admin/change-password/', platform_companies.platform_admin_change_password, name='platform_admin_change_password'),
    path('platform/company-imports/', platform_companies.platform_company_import_batches, name='platform_company_import_batches'),
    path('platform/company-imports/preview/', platform_companies.platform_company_import_preview, name='platform_company_import_preview'),
    path('platform/company-imports/<int:batch_id>/commit/', platform_companies.platform_company_import_commit, name='platform_company_import_commit'),
    path('platform/company-imports/template/', platform_companies.platform_company_import_template, name='platform_company_import_template'),
    path('platform/company-credentials/workbook/', platform_companies.platform_company_credentials_workbook, name='platform_company_credentials_workbook'),
    path('notifications/', notifications.notification_list, name='notification_list'),
    path('notifications/unread-count/', notifications.notification_unread_count, name='notification_unread_count'),
    path('notifications/read-template/', notifications.notification_mark_template_read, name='notification_mark_template_read'),
    path('notifications/<int:pk>/read/', notifications.notification_mark_read, name='notification_mark_read'),
    path('notifications/aggregate/', notifications.aggregate_notification_list, name='aggregate_notification_list'),
    path('notifications/aggregate/unread-count/', notifications.aggregate_notification_unread_count, name='aggregate_notification_unread_count'),
    path('notifications/aggregate/read/', notifications.aggregate_notification_mark_read, name='aggregate_notification_mark_read'),
    path('notifications/aggregate/read-all/', notifications.aggregate_notification_mark_all_read, name='aggregate_notification_mark_all_read'),

    # === BEGIN R4: M7+M8 routes ===
    path('search/', global_search.global_search, name='global_search'),
    # === END R4: M7+M8 routes ===

    
    

    
    path('templates/', templates.template_list_create, name='template_list'),
    path('templates/group-members/', templates.template_group_members, name='template_group_members'),
    path('templates/<int:pk>/', templates.template_detail, name='template_detail'),
    path('templates/<int:pk>/submit/', templates.template_submit, name='template_submit'),
    path('templates/<int:pk>/approve/', templates.template_approve, name='template_approve'),
    path('templates/<int:pk>/reject/', templates.template_reject, name='template_reject'),
    path('templates/<int:pk>/versions/', templates.template_versions, name='template_versions'),
    path('templates/<int:pk>/versions/<int:ver_id>/restore/', templates.template_version_restore, name='template_version_restore'),
    path('templates/<int:pk>/versions/<int:ver_id>/hide/', templates.template_version_toggle_hide, name='template_version_hide'),
    path('templates/<int:pk>/versions/<int:ver_id>/diff/', templates.template_version_diff, name='template_version_diff'),
    path('templates/<int:pk>/favorite/', templates.template_favorite, name='template_favorite'),
    path('templates/<int:pk>/export/', templates.template_export, name='template_export'),
    path('templates/import-docx/', templates.template_import_docx, name='template_import_docx'),
    path('templates/import-from-url/', templates.template_import_from_url, name='template_import_from_url'),
    path('trash/entries/', trash.trash_entries, name='trash_entries'),
    path('trash/restore/', trash.trash_restore, name='trash_restore'),
    path('trash/delete/', trash.trash_delete, name='trash_delete'),

    
    path('documents/', documents.document_list_create, name='document_list'),
    path('documents/upload/', documents.document_upload, name='document_upload'),
    path('documents/check-title/', documents.document_check_title, name='document_check_title'),
    path('documents/<int:pk>/', documents.document_detail_view, name='document_detail'),
    path('documents/<int:pk>/download/', documents.document_download, name='document_download'),
    path('documents/<int:pk>/summarize/', documents.document_summarize, name='document_summarize'),
    path('documents/<int:pk>/summarize-async/', documents.document_summarize_async, name='document_summarize_async'),
    path('document-summaries/', document_summaries.document_summary_discovery, name='document_summary_discovery'),
    path('document-summaries/suggest/', document_summaries.document_summary_suggest, name='document_summary_suggest'),
    path('document-summaries/<int:pk>/preview/', document_summaries.document_summary_preview, name='document_summary_preview'),
    path('document-summaries/<int:pk>/generate/', document_summaries.document_summary_generate, name='document_summary_generate'),
    # === BEGIN R2: M2+M4 routes ===
    path('document-summaries/<int:pk>/download/', document_summaries.document_summary_download, name='document_summary_download'),
    path('compliance-check/run/', compliance.compliance_check_run, name='compliance_check_run'),
    path('compliance-check/history/', compliance.compliance_check_history, name='compliance_check_history'),
    path('compliance-check/<int:pk>/', compliance.compliance_check_detail, name='compliance_check_detail'),
    # === END R2 ===
    path('documents/<int:pk>/preview-pdf/', documents.document_preview_pdf, name='document_preview_pdf'),
    path('documents/<int:pk>/download-pdf/', documents.document_download_pdf, name='document_download_pdf'),
    path('documents/<int:pk>/versions/<int:version>/download-pdf/', documents.document_version_download_pdf, name='document_version_download_pdf'),
    path('documents/<int:pk>/content-html/', documents.document_content_html, name='document_content_html'),
    path('documents/<int:pk>/forward/', documents.document_forward, name='document_forward'),
    path('templates/<int:pk>/preview-pdf/', documents.template_preview_pdf, name='template_preview_pdf'),
    path('templates/<int:pk>/content-html/', documents.template_content_html, name='template_content_html'),
    path('templates/<int:pk>/manual-edit/session/', template_manual_edit.template_manual_edit_session_create, name='template_manual_edit_session_create'),
    path('templates/manual-edit/provider-status/', template_manual_edit.template_manual_edit_provider_status, name='template_manual_edit_provider_status'),
    path('templates/manual-edit/sessions/<int:session_id>/', template_manual_edit.template_manual_edit_session_detail, name='template_manual_edit_session_detail'),
    path('templates/manual-edit/sessions/<int:session_id>/heartbeat/', template_manual_edit.template_manual_edit_session_heartbeat, name='template_manual_edit_session_heartbeat'),
    path('templates/manual-edit/sessions/<int:session_id>/finish/', template_manual_edit.template_manual_edit_session_finish, name='template_manual_edit_session_finish'),
    path('templates/manual-edit/sessions/<int:session_id>/cancel/', template_manual_edit.template_manual_edit_session_cancel, name='template_manual_edit_session_cancel'),
    path('templates/manual-edit/wopi/files/<uuid:file_id>', template_manual_edit.template_manual_edit_wopi_file, name='template_manual_edit_wopi_file'),
    path('templates/manual-edit/wopi/files/<uuid:file_id>/', template_manual_edit.template_manual_edit_wopi_file, name='template_manual_edit_wopi_file_slash'),
    path('templates/manual-edit/wopi/files/<uuid:file_id>/contents', template_manual_edit.template_manual_edit_wopi_contents, name='template_manual_edit_wopi_contents'),
    path('templates/manual-edit/wopi/files/<uuid:file_id>/contents/', template_manual_edit.template_manual_edit_wopi_contents, name='template_manual_edit_wopi_contents_slash'),
    path('documents/<int:pk>/signing/start/', signing.document_signing_start, name='document_signing_start'),
    path('documents/<int:pk>/signing/proposals/', signing.document_signing_proposal_create, name='document_signing_proposal_create'),
    path('documents/<int:pk>/finalize/', documents.document_finalize, name='document_finalize'),
    path('documents/<int:pk>/archive/', documents.document_archive, name='document_archive'),
    path('documents/<int:pk>/unarchive/', documents.document_unarchive, name='document_unarchive'),
    path('documents/<int:pk>/favorite/', documents.document_favorite, name='document_favorite'),
    path('documents/<int:pk>/share/', documents.document_share, name='document_share'),
    path('documents/<int:pk>/versions/', documents.document_versions, name='document_versions'),
    path('documents/<int:pk>/versions/<int:ver_id>/restore/', documents.document_version_restore, name='document_version_restore'),
    path('documents/<int:pk>/versions/<int:ver_id>/hide/', documents.document_version_toggle_hide, name='document_version_hide'),
    path('documents/<int:pk>/versions/<int:ver_id>/diff/', documents.document_version_diff, name='document_version_diff'),
    path('documents/<int:pk>/manual-edit/session/', document_manual_edit.document_manual_edit_session_create, name='document_manual_edit_session_create'),
    path('documents/manual-edit/provider-status/', document_manual_edit.document_manual_edit_provider_status, name='document_manual_edit_provider_status'),
    path('documents/manual-edit/sessions/<int:session_id>/', document_manual_edit.document_manual_edit_session_detail, name='document_manual_edit_session_detail'),
    path('documents/manual-edit/sessions/<int:session_id>/heartbeat/', document_manual_edit.document_manual_edit_session_heartbeat, name='document_manual_edit_session_heartbeat'),
    path('documents/manual-edit/sessions/<int:session_id>/finish/', document_manual_edit.document_manual_edit_session_finish, name='document_manual_edit_session_finish'),
    path('documents/manual-edit/sessions/<int:session_id>/cancel/', document_manual_edit.document_manual_edit_session_cancel, name='document_manual_edit_session_cancel'),
    path('documents/manual-edit/wopi/files/<uuid:file_id>', document_manual_edit.document_manual_edit_wopi_file, name='document_manual_edit_wopi_file'),
    path('documents/manual-edit/wopi/files/<uuid:file_id>/', document_manual_edit.document_manual_edit_wopi_file, name='document_manual_edit_wopi_file_slash'),
    path('documents/manual-edit/wopi/files/<uuid:file_id>/contents', document_manual_edit.document_manual_edit_wopi_contents, name='document_manual_edit_wopi_contents'),
    path('documents/manual-edit/wopi/files/<uuid:file_id>/contents/', document_manual_edit.document_manual_edit_wopi_contents, name='document_manual_edit_wopi_contents_slash'),
    path('word-ai/jobs/', word_ai_jobs.word_ai_job_list_create, name='word_ai_job_list_create'),
    path('word-ai/jobs/<int:pk>/', word_ai_jobs.word_ai_job_detail, name='word_ai_job_detail'),
    path('word-ai/jobs/<int:pk>/cancel/', word_ai_jobs.word_ai_job_cancel, name='word_ai_job_cancel'),
    path('word-ai/workers/claim/', word_ai_workers.word_ai_worker_claim, name='word_ai_worker_claim'),
    path('word-ai/workers/heartbeat/', word_ai_workers.word_ai_worker_heartbeat, name='word_ai_worker_heartbeat'),
    path('word-ai/jobs/<int:pk>/event/', word_ai_workers.word_ai_job_event, name='word_ai_job_event'),
    path('word-ai/jobs/<int:pk>/tool-loop/advance/', word_ai_workers.word_ai_job_tool_loop_advance, name='word_ai_job_tool_loop_advance'),
    path('word-ai/jobs/<int:pk>/mcp/advance/', word_ai_workers.word_ai_job_mcp_advance, name='word_ai_job_mcp_advance'),
    path('word-ai/jobs/<int:pk>/complete/', word_ai_workers.word_ai_job_complete, name='word_ai_job_complete'),
    path('word-ai/jobs/<int:pk>/fail/', word_ai_workers.word_ai_job_fail, name='word_ai_job_fail'),
    path('mailbox/', documents.mailbox_thread_list, name='mailbox_thread_list'),
    path('mailbox/<int:thread_id>/', documents.mailbox_thread_detail, name='mailbox_thread_detail'),
    path('mailbox/<int:thread_id>/verify/', documents.mailbox_thread_verify, name='mailbox_thread_verify'),
    path('mailbox/<int:thread_id>/preview-pdf/', documents.mailbox_thread_preview_pdf, name='mailbox_thread_preview_pdf'),
    path('mailbox/entries/<int:entry_id>/sign/', documents.mailbox_entry_sign, name='mailbox_entry_sign'),
    path('mailbox/entries/<int:entry_id>/forward/', documents.mailbox_entry_forward, name='mailbox_entry_forward'),
    path('mailbox/entries/<int:entry_id>/complete/', documents.mailbox_entry_complete, name='mailbox_entry_complete'),
    path('mailbox/entries/<int:entry_id>/reject/', documents.mailbox_entry_reject, name='mailbox_entry_reject'),
    path('mailbox/entries/<int:entry_id>/verify/', documents.mailbox_entry_verify, name='mailbox_entry_verify'),
    path('mailbox/entries/<int:entry_id>/preview-pdf/', documents.mailbox_entry_preview_pdf, name='mailbox_entry_preview_pdf'),

    
    path('signing/summary/', signing.signing_summary, name='signing_summary'),
    path('signing/candidates/', signing.signing_candidates, name='signing_candidates'),
    path(
        'signing/quick-sign/plans/<uuid:plan_token>/recipient/',
        signing.signing_quick_sign_plan_update_recipient,
        name='signing_quick_sign_plan_update_recipient',
    ),
    path(
        'signing/quick-sign/plans/<uuid:plan_token>/execute/',
        signing.signing_quick_sign_plan_execute,
        name='signing_quick_sign_plan_execute',
    ),
    path(
        'signing/quick-sign/plans/<uuid:plan_token>/dismiss/',
        signing.signing_quick_sign_plan_dismiss,
        name='signing_quick_sign_plan_dismiss',
    ),
    path('signing/proposals/pending-hr/', signing.signing_pending_hr_proposals, name='signing_pending_hr_proposals'),
    path('signing/proposals/<int:proposal_id>/approve/', signing.signing_proposal_approve, name='signing_proposal_approve'),
    path('signing/proposals/<int:proposal_id>/reject/', signing.signing_proposal_reject, name='signing_proposal_reject'),
    path('signing/tasks/', signing.signing_tasks, name='signing_tasks'),
    path('signing/tasks/<int:task_id>/', signing.signing_task_detail, name='signing_task_detail'),
    path('signing/tasks/<int:task_id>/signature-context/', signing.signing_task_signature_context, name='signing_task_signature_context'),
    path('signing/tasks/<int:task_id>/preview-pdf/', signing.signing_task_preview_pdf, name='signing_task_preview_pdf'),
    path('signing/tasks/<int:task_id>/sign/', signing.signing_task_sign, name='signing_task_sign'),
    path('signing/tasks/<int:task_id>/reject/', signing.signing_task_reject, name='signing_task_reject'),
    path('signing/delegations/', signing.signing_delegations, name='signing_delegations'),
    path('signing/delegations/<int:delegation_id>/', signing.signing_delegation_detail, name='signing_delegation_detail'),
    path('signed-pdfs/', signing.signed_pdf_list, name='signed_pdf_list'),
    path('signed-pdfs/<int:pk>/', signing.signed_pdf_detail, name='signed_pdf_detail'),
    path('signed-pdfs/<int:pk>/verify/', signing.signed_pdf_verify, name='signed_pdf_verify'),
    path('signed-pdfs/<int:pk>/preview-pdf/', signing.signed_pdf_preview_pdf, name='signed_pdf_preview_pdf'),
    path('signed-pdfs/<int:pk>/download/', signing.signed_pdf_download, name='signed_pdf_download'),

    
    path('ai/chat/', chat.chat_message, name='chat_message'),
    path('ai/chat-async/', chat.chat_message_async, name='chat_message_async'),
    path('ai/chat-model/', chat.chat_ai_model_info, name='chat_ai_model_info'),
    path('ai/chat/sessions/', chat.chat_sessions, name='chat_sessions'),
    path('ai/chat/sessions/<int:session_id>/messages/', chat.chat_session_messages, name='session_messages'),
    path('ai/rag/query/', chat.rag_query_view, name='rag_query'),
    path('ai/rag/sessions/', chat.rag_sessions, name='rag_sessions'),
    path('ai/rag/sessions/<int:session_id>/messages/', chat.rag_session_messages, name='rag_session_messages'),
    path('assistant/turn/', assistant.assistant_turn, name='assistant_turn'),
    path('assistant/turn-async/', assistant.assistant_turn_async, name='assistant_turn_async'),
    path('assistant/sessions/', assistant.assistant_sessions, name='assistant_sessions'),
    path('assistant/sessions/<int:session_id>/messages/', assistant.assistant_session_messages, name='assistant_session_messages'),
    path('assistant/audio/', assistant.assistant_audio_list, name='assistant_audio_list'),
    path('assistant/audio/<int:audio_id>/download/', assistant.assistant_audio_download, name='assistant_audio_download'),
    path('ai/doc/preview/', ai_doc.ai_doc_preview, name='ai_doc_preview'),
    path('ai/doc/preview-prompt/', ai_doc.ai_doc_preview_prompt, name='ai_doc_preview_prompt'),
    path('ai/doc/create/', ai_doc.ai_doc_create, name='ai_doc_create'),
    path('ai/doc/create-async/', ai_doc.ai_doc_create_async, name='ai_doc_create_async'),
    path('ai/doc/check-variables/', ai_doc.ai_doc_check_variables, name='ai_doc_check_variables'),
    path('ai/doc/extract-pdf/', ai_doc.ai_doc_extract_pdf, name='ai_doc_extract_pdf'),
    path('ai/doc/extract-pdf-async/', ai_doc.ai_doc_extract_pdf_async, name='ai_doc_extract_pdf_async'),
    path('ai/doc/extract-image/', ai_doc.ai_doc_extract_image, name='ai_doc_extract_image'),
    path('ai/doc/extract-image-async/', ai_doc.ai_doc_extract_image_async, name='ai_doc_extract_image_async'),
    path('ai/doc/prefill-profile/', ai_doc.ai_doc_prefill_profile, name='ai_doc_prefill_profile'),
    path('ai/doc/prefill-profile-async/', ai_doc.ai_doc_prefill_profile_async, name='ai_doc_prefill_profile_async'),
    path('ai/doc/prefill-company/', ai_doc.ai_doc_prefill_company, name='ai_doc_prefill_company'),
    path('ai/doc/prefill-company-async/', ai_doc.ai_doc_prefill_company_async, name='ai_doc_prefill_company_async'),

    # === BEGIN R3: M3+M6 routes ===
    path('prompts/compose-preview/', prompt_composer.prompt_compose_preview, name='prompt_compose_preview'),
    path('ai-tasks/inbox/', ai_tasks_views.task_inbox, name='ai_task_inbox'),
    path('ai-tasks/<uuid:task_id>/dismiss/', ai_tasks_views.task_dismiss, name='ai_task_dismiss'),
    # === END R3: M3+M6 routes ===

    path('ai-tasks/<uuid:task_id>/', ai_tasks_views.task_state, name='ai_task_state'),
    path('ai-tasks/<uuid:task_id>/cancel/', ai_tasks_views.task_cancel, name='ai_task_cancel'),

    path('users/peer-search/', users_search.peer_search, name='users_peer_search'),
    path('users/peer-search/filters/', users_search.peer_search_filters, name='users_peer_search_filters'),

    # === BEGIN R1: M1+M5 routes ===
    path('prompts/scopes/', prompts.prompt_scope_list, name='prompt_scope_list'),
    path('templates/<int:pk>/audience/', templates_peer.audience, name='template_audience'),
    path('documents/<int:pk>/audience/', documents_peer.audience, name='document_audience'),
    path('prompts/<int:pk>/audience/', prompts_peer.audience, name='prompt_audience'),
    # === END R1 ===

    path('templates/<int:pk>/peer-audience/', templates_peer.list_audience, name='template_peer_audience_get'),
    path('templates/<int:pk>/peer-audience/update/', templates_peer.update_audience, name='template_peer_audience_update'),

    path('documents/<int:pk>/peer-audience/', documents_peer.list_audience, name='document_peer_audience_get'),
    path('documents/<int:pk>/peer-audience/update/', documents_peer.update_audience, name='document_peer_audience_update'),

    path('prompts/<int:pk>/peer-audience/', prompts_peer.list_audience, name='prompt_peer_audience_get'),
    path('prompts/<int:pk>/peer-audience/update/', prompts_peer.update_audience, name='prompt_peer_audience_update'),

    # === Unified sharing endpoints (Phase 2 cua roadmap) ===
    path('groups/',
         sharing_views.shareable_group_list, name='shareable_group_list'),
    # entity_type ∈ {templates, documents, prompts}
    path('<str:entity_type>/<int:pk>/shares/',
         sharing_views.shares_list_create, name='shares_list_create'),
    path('<str:entity_type>/<int:pk>/shares/<int:grant_id>/',
         sharing_views.shares_detail, name='shares_detail'),
    path('<str:entity_type>/<int:pk>/shares/<int:grant_id>/submit/',
         sharing_views.shares_submit, name='shares_submit'),
    path('<str:entity_type>/<int:pk>/shares/<int:grant_id>/approve/',
         sharing_views.shares_approve, name='shares_approve'),
    path('<str:entity_type>/<int:pk>/shares/<int:grant_id>/reject/',
         sharing_views.shares_reject, name='shares_reject'),
    path('shares/pending/',
         sharing_views.shares_pending_inbox, name='shares_pending_inbox'),
    path('shares/shared-with-me/',
         sharing_views.shares_shared_with_me, name='shares_shared_with_me'),

    path('prompts/', prompts.prompt_list_create, name='prompt_list'),
    path('prompts/check/', prompts.prompt_check, name='prompt_check'),
    path('prompts/recent-used/', prompts.prompts_recent_used, name='prompts_recent_used'),
    path('prompts/<int:pk>/', prompts.prompt_detail, name='prompt_detail'),
    path('prompts/<int:pk>/submit/', prompts.prompt_submit, name='prompt_submit'),
    path('prompts/<int:pk>/approve/', prompts.prompt_approve, name='prompt_approve'),
    path('prompts/<int:pk>/reject/', prompts.prompt_reject, name='prompt_reject'),

    
    path('admin/ollama-models/', admin_v.ollama_models, name='admin_ollama_models'),
    path('admin/users/', company_admin.user_list, name='admin_users'),
    path('admin/users/<int:pk>/', company_admin.user_detail, name='admin_user_detail'),
    path('admin/groups/', company_admin.group_list, name='admin_groups'),
    path('admin/groups/<int:pk>/', company_admin.group_detail, name='admin_group_detail'),
    path('admin/groups/<int:pk>/members/', company_admin.group_members, name='admin_group_members'),
    path('admin/groups/<int:pk>/members/<int:user_id>/', company_admin.group_member_detail, name='admin_group_member_detail'),
    path('admin/departments/', company_admin.department_list, name='admin_departments'),
    path('admin/departments/<int:pk>/', company_admin.department_detail, name='admin_department_detail'),
    path('admin/positions/', company_admin.position_list, name='admin_positions'),
    path('admin/positions/<int:pk>/', company_admin.position_detail, name='admin_position_detail'),
    path('admin/ai-config/', company_admin.ai_config, name='admin_ai_config'),

    path('admin/backups/', company_backups.backup_list_create, name='cb_list_create'),
    path('admin/backups/components/', company_backups.backup_components, name='cb_components'),
    path('admin/backups/settings/', company_backups.backup_settings, name='cb_settings'),
    path('admin/backups/settings/set-password/', company_backups.backup_set_password, name='cb_set_password'),
    path('admin/backups/settings/verify-password/', company_backups.backup_verify_password, name='cb_verify_password'),
    path('admin/backups/<int:pk>/', company_backups.backup_detail, name='cb_detail'),
    path('admin/backups/<int:pk>/progress/', company_backups.backup_progress, name='cb_progress'),
    path('admin/backups/<int:pk>/download/', company_backups.backup_download, name='cb_download'),
    path('admin/backups/<int:pk>/restore/', company_backups.backup_restore, name='cb_restore'),

    # === BEGIN R5: M9+M10 routes ===
    path('admin/backups/<int:pk>/verify/', company_backups.backup_verify, name='cb_verify'),
    path('platform/companies/<int:pk>/dashboard/', platform_companies.platform_company_dashboard, name='platform_company_dashboard'),
    path('platform/companies/<int:pk>/activity/', platform_companies.platform_company_activity, name='platform_company_activity'),
    # === END R5 ===

    path('admin/company-context/', company_admin.company_context_read, name='company_context_read'),
    path('admin/import-users/', company_admin.import_users_excel, name='admin_import_users'),
    path('admin/import-users/template/', company_admin.import_users_template, name='admin_import_template'),

    
    path('admin/backup/', admin_v.backup_list, name='admin_backup_list'),
    path('admin/backup/create/', admin_v.backup_create, name='admin_backup_create'),
    path('admin/backup/<str:filename>/download/', admin_v.backup_download, name='admin_backup_download'),
    path('admin/backup/<str:filename>/', admin_v.backup_delete, name='admin_backup_delete'),

    
    path('dashboard/stats/', dashboard.dashboard_stats, name='dashboard_stats'),
    path('dashboard/org-node-stats/<int:user_id>/', dashboard.dashboard_org_node_stats, name='dashboard_org_node_stats'),

    
    path('templates/<int:pk>/generate-tags/', templates.template_generate_tags, name='template_generate_tags'),

    
    path('templates/<int:pk>/replace-docx/', bulk_upload.template_replace_docx, name='template_replace_docx'),

    
    path('templates/bulk/parse-excel/', bulk_upload.bulk_parse_excel, name='bulk_parse_excel'),
    path('templates/bulk/upload-single/', bulk_upload.bulk_upload_single, name='bulk_upload_single'),
    path('templates/bulk/sample/', bulk_upload.bulk_upload_sample, name='bulk_upload_sample'),

    
    path('guest/session/', guest_portal_cookie.guest_session_info, name='guest_session'),
    path('guest/session/cleanup/', guest_portal_cookie.guest_cleanup, name='guest_cleanup'),
    path('guest/parse/', guest_portal_cookie.guest_parse_template, name='guest_parse'),
    path('guest/parse-info/', guest_portal_cookie.guest_parse_info, name='guest_parse_info'),
    path('guest/parse-pdf/', guest_portal_cookie.guest_parse_pdf, name='guest_parse_pdf'),
    path('guest/generate/', guest_portal_cookie.guest_generate, name='guest_generate'),
    path('guest/document/', guest_portal_cookie.guest_document_detail, name='guest_document_detail'),
    path('guest/document/content-html/', guest_portal_cookie.guest_document_content_html, name='guest_document_content_html'),
    path('guest/document/download/', guest_portal_cookie.guest_document_download, name='guest_document_download'),
]
